npgsql/efcore.pg

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
The script output from migrations was causing errors due to alter column not being properly terminated.
> Adds statement terminator to end of ALTER COLUMN default statements

- doc/index.md
and give an example of Npgsql connection string for those who may be unsure
> Update documentation to 2.0.0

- test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
- test/EFCore.PG.FunctionalTests/TestUtilities/TestNpgsqlRetryingExecutionStrategy.cs
This makes resharper solution-wide analysis happy again (green checkmark).
There are tests failing due to what seems like datetime format, I'll dig into them as well.
> Fix cosmetic solution bugs triggering resharper solution errors.

- src/EFCore.PG/FullTextSearch/NpgsqlFullTextSearchDbFunctionsExtensions.cs
- src/EFCore.PG/FullTextSearch/NpgsqlFullTextSearchLinqExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
- src/EFCore.PG/Query/Expressions/Internal/FullTextSearchExpression.cs
- test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
@roji This is a follow up to #315 that implements a few missing methods and operators for full text search and resolves issue #373:
1. tsvector concat operator (Concat extension method on NpgsqlTsVector)
2. ts_delete function (single lexeme and array of lexemes overload).
3. ts_filter function
4. array_to_tsvector function.
There is a caveat however, due to limitations in EF Core, all functions that take array parameters can only accept constant values (ie: the array must be computable outside the query). Attempts to use an array with elements that come from range variables from tables will result in NotSupportedException being thrown from deep within EF Core itself.
> Full text search follow up

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRangeTranslator.cs
The `NpgsqlRangeTranslator` merged in #323 uses nameof(...) without checking the declaring type. This returns the unqualified name, such that all methods named `Contains` (for example) that reach this translator are translated to the range operator.
This commit adds a check to screen for the declaring type.
> Bug fix for #323

- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
Submitting based on https://github.com/npgsql/npgsql/pull/1939#discussion_r189436527:
> Unrelated, but I just realized I replicated this logic in the EF Core provider's [`NpgsqlRangeTypeMapping.GenerateNonNullSqlLiteral()`](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/blob/14d4579c59f42c3319cfa39fc0bcd0adca6a3c8a/src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs#L61). Do you want to compare the two and submit a PR which makes EF Core simply call `ToString()`?
An important consideration for this PR is the loss of specialized handling for the bounds.
> Simplify NpgsqlRangeTypeMapping

- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs
```c#
PgFunction("abbrev", typeof(string), new [] { inetExpression }) 
// where inetExpression is something like x => x.Inet
```
```sql
-- before:
SELECT abbrev(x."Inet", );
-- after:
SELECT abbrev(x."Inet");
```
Also includes general cleanup to match project style, remove unused using-statements, etc.
> Bug fix in NpgsqlQuerySqlGenerator with PgFunctionExpression

- QueryBaseline.cs
- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
When a custom binary operator uses a standard comparison operator (`=`, `<>`, `<`, `>`, `<=`, `>=`) EF Core will generate a pattern that causes a syntax error in PostgreSQL.
Example SQL:
```sql
WHERE x."Inet" < @__inet_1 = TRUE
```
This patch adds logic to check if the custom binary operator is one of the standard comparison operators. If so, it wraps the expression in parenthesis.
Example SQL (patched):
```sql
WHERE (x."Inet" < @__inet_1) = TRUE
```
While it seems like this could be avoided by having the custom translator construct a standard `Expression.LessThan(Expression,Expression)`, this causes an error to be thrown...because the binary operator isn't defined.
Example stack trace:
```
System.InvalidOperationException : The binary operator LessThanOrEqual is not defined
for the types …
```
> Patch for custom binary operators that use standard comparison symbols

- doc/mapping/full-text-search.md
- doc/mapping/general.md
@roji Here's the documentation page for full text search. Let me know what you think. This is a follow up to #1.
> Full text search documentation page

- src/EFCore.PG.NTS/NetTopologySuiteGeographyTypeMapping.cs
- src/EFCore.PG.NTS/NetTopologySuiteGeometryTypeMapping.cs
The WKT doesn't include the SRID. Luckily, PostGIS accepts an extended format that includes it.
> NTS: Preserve SRID

- doc/mapping/full-text-search.md
@rwasef1830 @YohDeadfall @austindrenski here are some proposed additions/amendments to the full-text-search docs:
* Document expression index method in addition to trigger-updated tsvector column
* Remove portions of the code samples which don't really concern full text search
* Adapt samples and operation table to be more coherent with the rest of the docs site.
Let me know what you guys think.
> Additions and changes to full-text search docs

- src/EFCore.PG/Extensions/NpgsqlDbContextOptionsExtensions.cs
Splits off some unrelated cleanup from #483
> Add some doc comments, align styles

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
Moving common changes from #431 and #483.
> Add doc comments and refactor composite translators

- src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Internal/NpgsqlOptions.cs
Moving common changes from #431 and #483.
> Add doc comments and refactor options classes

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlNetworkTranslator.cs
- src/EFCore.PG/Query/Internal/NpgsqlEvaluatableExpressionFilter.cs
- test/EFCore.PG.FunctionalTests/Query/NetworkQueryNpgsqlTest.cs
- `IPAddress.Parse(string)`
- `PhysicalAddres.Parse(string)`
#534
> Add support to parse IP and MAC addresses

- src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeExpressionFragmentTranslator.cs
> Add composite expression fragment translator

- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs
- Add doc comments
- Reorganize methods into regions for `Generators` and `Visitors`
- Make new methods `virtual` for consistency
- Add `[NotNull]` to params on new methods for consistency
> Refactor SQL generator

- src/EFCore.PG/Query/Expressions/Internal/ArrayAnyAllExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/AtTimeZoneExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/CustomBinaryExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/CustomUnaryExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/ExplicitStoreTypeCastExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/ILikeExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/PgFunctionExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/RegexMatchExpression.cs
- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs
~~We have several custom expression types that use the `ExpressionType.Extension`. These can be visited by overriding `VisitExtension(...)` rather than explicitly dispatching from the `Expression.Accept(...)` method.~~
~~This is partially cosmetic, but it also clarifies where we are (and are not) perturbing the normal behavior of a generic `ExpressionVisitor` pattern. Further, this also reduces the public API surface of the various expression visitors by moving all of the custom visits from `public` to `protected`.~~
Repurposing this PR to add doc comments and cleanup some inconsistencies in the extension expressions. 
Moved from #541.
> Cleanup and refactor extension expressions

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
Hey @roji,
This should fix #562 
It turns out while I was implementing the Matches operator function, I had misread the PostgreSQL docs, specifically this part in https://www.postgresql.org/docs/current/static/textsearch-intro.html:
> > tsvector @@ tsquery
> > tsquery  @@ tsvector
> > text @@ tsquery
> > text @@ text
>
> The first two of these we saw already. The form text @@ tsquery is equivalent to to_tsvector(x) @@ y. The form text @@ text is equivalent to to_tsvector(x) @@ plainto_tsquery(y).
I imagined there was a `tsvector @@ text` overload and implemented a `Matches` method that took a string parameter in addition to the overload that takes `NpgsqlTsQuery`. Strangely enough, the unit test for this was passing but I now I think that it was due to the test passing the string as a …
> In case of @@ operator with string RHS, wrap RHS with plain_totsquery.

- src/EFCore.PG/Extensions/NpgsqlRangeExtensions.cs
- Patch for #570.
- `NpgsqlRange<T>` doesn't implement `IComparable<T>`, so drop the constraint.
> Drop IComparable<T> constraint for range extensions

- src/EFCore.PG.NodaTime/NodaTimeDbContextOptionsExtensions.cs
- src/EFCore.PG.NodaTime/NodaTimeEvaluatableExpressionFilter.cs
- src/EFCore.PG.NodaTime/NodaTimeMappings.cs
- src/EFCore.PG.NodaTime/NodaTimeMemberTranslator.cs
- src/EFCore.PG.NodaTime/NodaTimeMethodCallTranslator.cs
- src/EFCore.PG.NodaTime/NodaTimePlugin.cs
- src/EFCore.PG/Query/EvaluatableExpressionFilters/Internal/NpgsqlFullTextSearchEvaluatableExpressionFilter.cs
- test/EFCore.PG.Plugins.FunctionalTests/NodaTimeTest.cs
Translates `SystemClock.Instance.GetCurrentInstant()` to `NOW() AT TIME ZONE 'UTC'`.
#502
> Translate SystemClock.GetCurrentInstant() for NodaTime

- src/EFCore.PG.NodaTime/NodaTimeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/NpgsqlDateTimeMemberTranslator.cs
Fixes: #576 
This PR moves the `NpgsqlDateTimeMemberTranslator` out of the Internal namespace so that it can be inherited in the NodaTime plugin so that both classes can share the same (updated) `GetDatePartExpression(...)`.
> Refactor DateTime member translator for plugins

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Where.cs
Queries with `DateTime.Today` used in-memory filtering.  I'm not sure I follow how these unit tests work. Let me know if I need to make any changes and I'll watch for CI errors. 
```c#
ctx.SomeEntity.Where(s => s.CreatedDate == DateTime.Today);
```
```sql
SELECT * 
FROM "SomemEntity" AS s 
WHERE s."CreatedDate" == DATE_TRUNC('date', NOW());
```
> Translate DateTime.Today

- src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Internal/NpgsqlOptions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateAddTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/CompatibilityQueryNpgsqlTest.cs
> Add support for backend compatibility (#483)

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
Make `NpgsqlMigrationsSqlGenerator` compatibility-version aware.
#607
> Inject compatibility version for migrations

- doc/mapping/range.md
- doc/release-notes/2.2.md
- doc/toc.md
- src/EFCore.PG.NodaTime/NodaTimePlugin.cs
- src/EFCore.PG/Extensions/NpgsqlModelBuilderExtensions.cs
- src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Internal/NpgsqlOptions.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Metadata/NpgsqlModelAnnotations.cs
- src/EFCore.PG/Metadata/PostgresEnum.cs
- src/EFCore.PG/Metadata/PostgresRange.cs
- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
* Added an Npgsql options extension to allow users to map user-defined   ranges.
* Added modeling for range types, to allow creation of user-defined range types in migrations.
* Simplified and improved range mapping.
Closes #329
> Support user-defined ranges

- src/EFCore.PG.NTS/NetTopologySuiteMethodCallTranslator.cs
- src/EFCore.PG/Extensions/NpgsqlDbFunctionsExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlConvertTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateAddTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlLikeTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRegexIsMatchTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringContainsTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringEndsWithTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringIndexOfTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringIsNullOrWhiteSpaceTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringLengthTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringReplaceTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringStartsWithTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringSubstringTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringTrimTranslator.cs
- src/EFCore.PG/Query/ExpressionVisitors/NpgsqlSqlTranslatingExpressionVisitor.cs
Just going through and doing some housekeeping in `Npgsql.EntityFrameworkCore.PostgreSQL.Query`.
This includes some refactoring (mostly Rider auto-fixes + some pattern matching), so the refactors should be pure, but if something looks questionable, I'm happy to revert.
/cc @roji @YohDeadfall @rwasef1830
> Cleanup style and document public API surfaces

- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlStringTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/Query/CharacterQueryNpgsqlTest.cs
This is an attempt to patch #567 in which an exception is thrown due to a conflict between changes detected by the CLR and the number of records changed in the database.
The key here is to modify the way parameter values are compared in the CLR by overriding `Comparer` and `KeyComparer` with a `ValueComparer<string>` that uses PostgreSQL `character` semantics.
Fixes: #567
> Update mapping for character(n)

- NuGet.config
- doc/mapping/enum.md
- src/EFCore.PG.NTS/EFCore.PG.NTS.csproj
- src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj
- src/EFCore.PG/EFCore.PG.csproj
- src/EFCore.PG/Extensions/NpgsqlModelBuilderExtensions.cs
- test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
- test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
- test/EFCore.PG.Plugins.FunctionalTests/EFCore.PG.Plugins.FunctionalTests.csproj
- test/EFCore.PG.Tests/EFCore.PG.Tests.csproj
Closes: #620
- `PgNameAttribute` is respected for the type and members.
- Default translator from `NpgsqlConnection.GlobalTypeMapper.DefaultNameTranslator`
#605
> Add inference-based overload to ForNpgsqlHasEnum

- test/EFCore.PG.FunctionalTests/NpgsqlDatabaseCreatorTest.cs
These tests have been flaky for long and we haven't had time to investigate. Disabling until we do.
@austindrenski, @YohDeadfall just in case you feel like trying to understand the actual issue...
> Disable NpgsqlDatabaseCreatorTest

- src/EFCore.PG/EFCore.PG.csproj
- test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
- test/EFCore.PG.Tests/EFCore.PG.Tests.csproj
I'm seeing package downgrade errors while publishing self-contained apps referencing the provider.
Bumping the dependencies to `2.1.3` for `hotfix/2.1.3` to resolve.
> Target EF Core 2.1.3

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
Simple refactoring for https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/607
@roji, let's continue our discussion here
> Simplify NpgsqlMigrationsSqlGenerator.Generate for CreateSequenceOperation

- src/EFCore.PG/Extensions/NpgsqlRangeExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRangeTranslator.cs
- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
> Translate simple range operators + compatibility support

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeExpressionFragmentTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs
- src/EFCore.PG/Query/ExpressionVisitors/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
> Updates split off from PR 541

- src/EFCore.PG/Extensions/NpgsqlModelBuilderExtensions.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
- If no schema is specified in `.ForNpgsqlHasEnum(...)`, then use the default schema annotation.
- Properly quote schema-qualified enums for literal generation and mapping (override `StoreType`).
- Cache mappings from CLR values to PostgreSQL labels.
Fixes: #554 
Fixes: #593
> Update enum quoting and default schema use

- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
- src/EFCore.PG/Metadata/INpgsqlIndexAnnotations.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Metadata/NpgsqlIndexAnnotations.cs
- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Utilities/Check.cs
- test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
Just picking up the good work done by @quanterion in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/257.
I tried looking at scaffolding support as well, but it was a bit involved, so figured I'd punt on it for now and focus on getting the runtime support in.
Closes https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/481
> Add support for index operators

- src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Internal/NpgsqlOptions.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.Tests/EFCore.PG.Tests.csproj
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
Fixes #688 
Note the rename from RangeMappingInfo to UserRangeDefinition... While working on this it got confusing, as RangeMappingInfo wasn't a MappingInfo in the strict EF Core sense. I've left the public-facing `MapRange()` method on NpgsqlDbContextOptionsBuilder, partially to avoid breaking existing code, and partially because it seems acceptable to call this "mapping" in user-facing APIs, while internally it produces a "definition".
> Fix range mapping

- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
- src/EFCore.PG/Metadata/INpgsqlIndexAnnotations.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Metadata/NpgsqlIndexAnnotations.cs
- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
> Add support for INCLUDE clause in indexes

- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlTestStore.cs
> Scaffold index operators and included (covered) index columns

- src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs
- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Metadata/PostgresRange.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
- test/EFCore.PG.Plugins.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
- test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchFactoryTest.cs
- test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchTest.cs
- If no schema is specified in `.ForNpgsqlHasRange(...)`, then use the default schema annotation.
- Properly quote schema-qualified ranges for literal generation and mapping (override `StoreType`).
> Update range mapping for schema-qualified and quoted ranges

- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
These changes are split out from #685 which currently includes both obvious refactorings and more subtle changes to how we construct enum annotations. Once this is merged, I'll rebase #685 so that it includes only the annotation-related changes.
These were already approved in #685 so I'm going to go ahead and merge this as soon as the tests pass.
/cc @roji @YohDeadfall
> Schema enums follow up (part 1)

- src/EFCore.PG.NTS/Storage/Internal/NpgsqlNetTopologySuiteTypeMappingSourcePlugin.cs
- test/EFCore.PG.Tests/Storage/NpgsqlNetTopologySuiteTypeMappingSourcePluginTest.cs
We previously generated PostgreSQL GEOMETRY (or GEOGRAPHY) columns, not
taking into account the CLR type. We now include that as a constraint on
the column.
Note that SRID support still needs to be done (#717).
Fixes #719
> Generate GEOMETRY (POINT) columns

- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Metadata/PostgresEnum.cs
- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
> Schema enums follow up (part 2)

- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Metadata/PostgresRange.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
> Refactor range metadata

- QueryBaseline.cs
- src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
> Implemented IGeometry.IsWithinDistance using ST_DWithin

- .appveyor.yml
- Directory.Build.props
- src/Directory.Build.props
- src/EFCore.PG.NTS/EFCore.PG.NTS.csproj
- src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj
- src/EFCore.PG/EFCore.PG.csproj
- test/Directory.Build.props
- test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
- test/EFCore.PG.Plugins.FunctionalTests/NetTopologySuiteTest.cs
- test/EFCore.PG.Tests/EFCore.PG.Tests.csproj
- Updates `hotfix/2.1.4` to manage package versions with `Directory.Build.props` as on `dev`.
- Bumps dependency patch versions:
Package | From | To
--|--|--
`Microsoft.EntityFrameworkCore*` | `2.1.3` | `2.1.4`
`Microsoft.NET.Test.Sdk` | `15.7.2` | `15.9.0`
`Npgsql` | `4.0.3` | `4.0.4`
`Npgsql.*` | `1.0.*` | `4.0.4`
`SourceLink.Create.CommandLine` | `2.8.1` | `2.8.3`
`xunit*` | `2.3.1` | `2.4.1`
> Update patch versions

- .appveyor.yml
- test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
- test/EFCore.PG.Plugins.FunctionalTests/EFCore.PG.Plugins.FunctionalTests.csproj
- test/EFCore.PG.Tests/EFCore.PG.Tests.csproj
It looks like we missed the test suites when updating versions before the `2.2` release. Moving the targets from `netcoreapp2.1` to `netcoreapp2.2`.
Planning to merge once the tests have passed.
/cc @roji
> Bump test projects to target `netcoreapp2.2`

- .github/CODEOWNERS
This adds [a GitHub CODEOWNERS file](https://help.github.com/articles/about-codeowners/), which is supposed to automatically request reviews on every pull requested submitted to the repo.
Assuming you guys are interested in being involved in every change, this will make it easier to manage the process. I propose that by default we continue as we have up to now, i.e. wait for all three of us to review before merging (aside from trivial changes). If anyone sees that they have no time (or interest) in reviewing a particular PR, we can just leave a comment saying that, and merge without that person's approval. Does that sound like a good process?
PS I can also add the same on the http://github.com/npgsql/npgsql/ repo, let me know if that's OK for you.
> Add CODEOWNERS files

- Directory.Build.props
- src/EFCore.PG.NTS/EFCore.PG.NTS.csproj
- src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj
- src/EFCore.PG/EFCore.PG.csproj
Our own version is now separate from the EF Core version we depend on. This is important since during regular we need to have version 3.0.0 (the CI suffix will later be tacked on at the build server), while we depend on something like 3.0.0-preview.18572.1.
Note that still depend on EF Core 2.2, porting to 3.0.0-preview1 is ongoing in a separate branch.
> Bump our version to 3.0, clean up versions

- Directory.Build.props
- src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs
- src/EFCore.PG/Query/EvaluatableExpressionFilters/Internal/NpgsqlFullTextSearchEvaluatableExpressionFilter.cs
- src/EFCore.PG/Query/EvaluatableExpressionFilters/Internal/NpgsqlNodaTimeEvaluatableExpressionFilter.cs
- src/EFCore.PG/Query/EvaluatableExpressionFilters/Internal/ReLinqNpgsqlCompositeEvaluatableExpressionFilter.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlConvertTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs
- src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGeneratorFactory.cs
- test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/CustomConvertersNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NetworkQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Functions.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Where.cs
- test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs
This makes the provider compile against the recently-released EF Core 3.0.0-preview.18572.1. Some minor changes were necessary, and some tests were disabled because of EF Core-side changes (especially https://github.com/aspnet/EntityFrameworkCore/issues/14159).
All tests pass, once this is merged I'll release our own 3.0.0-preview1.
> Changes for 3.0.0-preview1

- EFCore.PG.sln.DotSettings
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs
Fixes: #787
_Note that the NodaTime plugin already does this since the NodaTime formatters using the invariant culture by default._
> Format date/time literals using invariant culture

- Directory.Build.props
Note that packages in `Microsoft.Extensions.*` [were not updated](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.1/2.2.1.md#packages-updated-in-this-release) in this release.
> Bump packages to 2.2.1

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
This fixes issue #809 by always explicitly casting the config parameter in all relevant function calls to regconfig using `ExplicitStoreTypeCastExpression`.
> Fix issue #809

- src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs
Re: https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/813. Follows EF Core's lead; https://github.com/aspnet/EntityFrameworkCore/pull/14641.
> Remove non-generic Npgsql-specific HasIndex extension method

- .appveyor.yml
- .build/setup_appveyor.ps1
> Update CI for PostgreSQL 11.1, PostGIS 2.5.1

- src/EFCore.PG.NTS/Storage/Internal/NpgsqlGeometryTypeMapping.cs
- src/EFCore.PG.NTS/Storage/Internal/NpgsqlNetTopologySuiteTypeMappingSourcePlugin.cs
- test/EFCore.PG.Tests/EFCore.PG.Tests.csproj
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
When dealing with spatial store type names (e.g. scaffolding), we
supported geometry/geography, but only when no facets were
specified. We now support geometry(point,4326) etc.
Fixes #818
> Support faceted spatial store type names

- QueryBaseline.cs
- src/EFCore.PG/Extensions/NpgsqlFullTextSearchDbFunctionsExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
This resolves half of issue #629
> Implement DbFunctions extensions for websearch_to_tsquery (#629)

- doc/modeling/indexes.md
~`HasIndex(Expression<Func<TEntity,Object>>)` returns `IndexBuilder` instead of `IndexBuilder<TEntity>`, so no overload of `ForNpgsqlInclude` accept `Expression<Func<TEntity, object>>` now.~
This could be merged after targeting a newer version of EFCore, which has the corresponding `HasIndex()` overload.
> [WIP] Update doc as #821.

- QueryBaseline.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
Follow up to #753 
CC @austindrenski @CornedBee
> Follow up to #753. Explicitly cast config to regconfig.

- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
- src/EFCore.PG/Metadata/INpgsqlIndexAnnotations.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Metadata/NpgsqlIndexAnnotations.cs
- src/EFCore.PG/Metadata/NullSortOrder.cs
- src/EFCore.PG/Metadata/SortOrder.cs
- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- src/EFCore.PG/Utilities/SortOrderHelper.cs
- test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
> Add support for index sort options

- src/EFCore.PG.NodaTime/Storage/Internal/NodaTimeMappings.cs
- src/EFCore.PG.NodaTime/Utilties/Util.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTypeMapping.cs
- test/EFCore.PG.Plugins.FunctionalTests/EFCore.PG.Plugins.FunctionalTests.csproj
- test/EFCore.PG.Plugins.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
Not done: Instant, ZonedDateTime and Period, which require features not yet supported by the EF Core code generator.
This PR is meant to be backported to 2.2.x. I'll try to work on code generation improvements in EF Core to enable the rest of the types for 3.0.
Closes #713
> Add literal code generation for some NodaTime types

- doc/mapping/full-text-search.md
The trigger name which gets generated (`product_search_vector_update`):
``` csharp
migrationBuilder.Sql(
@"CREATE TRIGGER product_search_vector_update BEFORE INSERT OR UPDATE
ON ""Products"" FOR EACH ROW EXECUTE PROCEDURE
tsvector_update_trigger(""SearchVector"", 'pg_catalog.english', ""Name"", ""Description"");");
```
should match the one being deleted:
``` csharp
migrationBuilder.Sql("DROP TRIGGER product_search_vector_update");
```
instead of:
``` csharp
migrationBuilder.Sql("DROP TRIGGER product_search_vector");
```
> Corrects the name in the doc of the full-text-search-trigger to drop

- src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMemberTranslatorPlugin.cs
- src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
Added `Geometry.Buffer(double, int)`
Added `Geometry.InteriorPoint`
Added `Geometry.OgcGeometryType`
Added `Geometry.Union()`
Contributes to #457
> Added new NTS translations

- src/EFCore.PG/Metadata/PostgresExtension.cs
Closes: #899 
Add v 2.1 extensions annotations values compatibility: consider '' value as null.
> Extensions creation backward compatibility fix

- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
Important to make sure separate service providers are created when different context options are specified.
> Add missing GetServiceProviderHashCode() to NpgsqlOptionsExtensions

- azure-pipelines.yml
The dotnet CLI task produces `*.symbols.nupkg` instead of the newer `.snupkg` format. Ignore both for now.
_Note: since theses tasks don't trigger on PR builds, the issue is only observable after merge._
#646
#928 
#929
> Ignore legacy symbol package format

- src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlEntityTypeExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlIndexExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlModelBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlModelExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlPropertyBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlPropertyExtensions.cs
- src/EFCore.PG/Infrastructure/NpgsqlModelValidator.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlStoreGenerationConvention.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationConvention.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationStrategyConvention.cs
- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
- src/EFCore.PG/ValueGeneration/Internal/NpgsqlValueGeneratorCache.cs
- src/EFCore.PG/ValueGeneration/Internal/NpgsqlValueGeneratorSelector.cs
- test/EFCore.PG.Tests/Metadata/NpgsqlBuilderExtensionsTest.cs
- test/EFCore.PG.Tests/Metadata/NpgsqlMetadataBuilderExtensionsTest.cs
- test/EFCore.PG.Tests/Metadata/NpgsqlMetadataExtensionsTest.cs
Fixes #942
Following https://github.com/aspnet/EntityFrameworkCore/issues/16773
> Rename provider specific core metadata extensions

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
If a system column was present when creating a table, we filtered it out by creating a copy of CreateTableOperation. We didn't copy across all fields, so comments didn't get created.
Switched to the less brutal practice of mutating the operation in place to remove columns instead of creating a copy.
Fixes #834
> Fix system column filtering in migrations

- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlEntityTypeExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlPropertyBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlPropertyExtensions.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
Unlike the previous attempt in #950, this doesn't exactly conserve backwards compatibility by recognizing the old annotations, so applying old migrations will not generate the comments. However, the previous obsoleted builder methods (ForNpgsqlHasComment) now simply call the new ones, and the first time a migration is generated after upgrading to 3.0.0 the comments will be recreated.
This cleans up the source code, and seems acceptable as this is a rarely-used feature with no functional impact.
Closes #892
> New EF Core comment support (take 2)

- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
- test/EFCore.PG.FunctionalTests/LoggingNpgsqlTest.cs
This repo has not been updated to use a new enough version (>4.1) of Npgsql yet for this to compile. I didn't want to charge ahead and do that as it seems outside the scope of this PR to do that upgrade, but it is required for this PR as it uses the new member `ProvidePasswordCallback` on `NpgsqlConnection` which was added in https://github.com/npgsql/npgsql/pull/2502
> Add support for ProvidePasswordCallback to EFCore.PG

- Directory.Build.props
- EFCore.PG.sln.DotSettings
- src/EFCore.PG/Extensions/NpgsqlJsonDbFunctionsExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlNetworkExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonDomTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs
- src/EFCore.PG/Query/Expressions/Internal/JsonTraversalExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/SqlCustomBinaryExpression.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlExpressionFactory.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Issue #981 enabled mapping arbitrary user POCOs to PG JON. This adds support for mapping the System.Text.Json DOM types JsonDocument and JsonElement, which are more relevant for unstructured scenarios. Traversal is implemented as well as some of the PG JSON operators.
One possible thing to "cast" strongly-typed POCOs as weakly-typed DOM types for the purposes of expressing [various JSON operations](https://www.postgresql.org/docs/current/functions-json.html), including [PG 12's upcoming support for jsonpath](https://www.postgresql.org/docs/12/functions-json.html).
Closes #1002
/cc @smitpatel @ajcvickers @divega @AndriySvyryd @maurycy @bricelam
Note: pushed the PR just before leaving so there may be some silliness (will go over it again tomorrow).
> Map JsonDocument and JsonElement

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
* If an AlterDatabaseOperation is created but an enum wasn't actually altered, don't do anything (we used to throw).
* Take schema into account when detecting old and new enums.
Fixes #979
Fixes #1027
> Correct enum migration logic

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
dotnet `string.Substring` has overload with one parameter, and postgres `SUBSTRING` has semantic equivalent arguments (optional length)
> Substring without length translation

- src/EFCore.PG/Query/Internal/NpgsqlEvaluatableExpressionFilter.cs
Unfortunately, it seems a filter is still required to run DbFunctions on ef core 3.0.
> Add support for PGroonga.EntityFrameworkCore EF.Functions

- Directory.Build.props
Per the [GPR docs](https://help.github.com/en/articles/configuring-nuget-for-use-with-github-package-registry#publishing-multiple-packages-to-the-same-github-repository), we need these fields to point at the correct repo.
I think this is why some CI packages for `Npgsql.EntityFrameworkCore.PostgreSQL` are showing up here https://github.com/npgsql/npgsql/packages instead of here https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/packages.
I've submitted a support ticket to GitHub asking how to delete/move/update the packages that are in the wrong place. I'll let you guys know when I hear back from them.
> Update repository and project urls

- src/EFCore.PG/Migrations/NpgsqlMigrationBuilderExtensions.cs
- test/EFCore.PG.Tests/NpgsqlMigrationBuilderTest.cs
Add extension method to be make it easier to detect if an Entity Framework Core migration is targeting a PostgreSQL database.
```csharp
public partial class MyDbMigration : Migration
{
protected override void Up(MigrationBuilder migrationBuilder)
{
if (migrationBuilder.IsNpgsql())
{
// ...
}
}
protected override void Down(MigrationBuilder migrationBuilder)
{
if (migrationBuilder.IsNpgsql())
{
// ...
}
}
}
```
> Add `IsNpgsql` extension method to EF's MigrationBuilder

- Directory.Build.props
... now that [the repo was renamed to `efcore.pg`](https://github.com/npgsql/efcore.pg/issues/1074)
> Update repository and project urls to match new repo name

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
> Use PERFORM within PL/pgSQL block to discard result

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Functions.cs
Which was done in #1068 to compensate for [a PG12 bug](https://www.postgresql.org/message-id/CADT4RqAz7oN4vkPir86Kg1_mQBmBxCp-L_%3D9vRpgSNPJf0KRkw%40mail.gmail.com).
/cc @austindrenski
> Revert off-by-one STRPOS change

- Directory.Build.targets
- NuGet.Config
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlNetworkTranslator.cs
- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
- src/EFCore.PG/ValueGeneration/Internal/NpgsqlSequenceHiLoValueGenerator.cs
- test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsWeakQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/GroupByQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonStringQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/QueryNoClientEvalNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Functions.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.ResultOperators.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs
As EF Core 3.1.0 is now frozen this should be the last sync.
The only notable change here is that some null optimizations on the EF Core side seem to have broken our use of ExpressionType.Not for network types and full text search. https://github.com/aspnet/EntityFrameworkCore/issues/18788 tracks fixing this on the EF Core side for 5.0, in the meantime I've hacked around this by using ExpressionType.Negate instead.
I've also tightened our array method translator to skip array expressions who's type mapping isn't an array mapping (to allow array properties mapped via value converters to work).
/cc @maumar @smitpatel @ajcvickers
> Sync with latest EF Core 3.1.0 preview3

- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
> Translate array overlap and containment

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/NullSemanticsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
Because it prevents index usage. Will reimplement after we can sniff the parameter for null values.
Fixes #1152
> Remove COALESCE from array ANY expression

- src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs
- src/EFCore.PG/Extensions/TypeExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs
- src/EFCore.PG/Query/Expressions/Internal/ArrayIndexExpression.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlExpressionFactory.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayArrayTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayListTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
* Match our List<T> translation capabilities to CLR array.
* Improve some mapping and inference aspects.
Closes #395
> Translate List<T> operations to PG array

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
Fixes #1210
No regression test, #1203 tracks that.
> Suppress transaction when creating an index concurrently

- src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
This failed when the column name wasn't the same as the property name.
Fixes #1201
~The same bug seems to exist in the SQL Server, opened https://github.com/dotnet/efcore/issues/19602. Once a regression test is done there (with the new migration tests, https://github.com/dotnet/efcore/issues/19039), we should port it to Npgsql too.~
> Fix migrations for index included properties

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
Fixes #1230
Regression test introduced in 5.0 (ComplexNavigationsQueryTestBase.Optional_navigation_inside_nested_method_call_translated_to_join_keeps_original_nullability_also_for_arguments)
> Fix SQL for DateTime.Add*

- src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs
As a bonus the code won't throw an exception when compiled with the checked option turned on.
> Changed parameter count type to int

- src/EFCore.PG/NpgsqlRetryingExecutionStrategy.cs
- src/EFCore.PG/Query/Internal/NpgsqlCompiledQueryCacheKeyGenerator.cs
- src/EFCore.PG/Storage/Internal/NpgsqlExecutionStrategy.cs
- test/EFCore.PG.FunctionalTests/CommandInterceptionNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/ExecutionStrategyTest.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlDbContextOptionsBuilderExtensions.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/TestNpgsqlConnection.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/TestNpgsqlRetryingExecutionStrategy.cs
- test/EFCore.PG.FunctionalTests/TransactionNpgsqlTest.cs
Includes test changes done in https://github.com/dotnet/efcore/pull/18691
Tests now run using retrying strategy, hopefully working around the transient exceptions we're seeing on CI since the migration tests.
Closes #1244
> Execution strategy fixes and sync

- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterTypeMapping.cs
- test/EFCore.PG.FunctionalTests/Query/QueryBugTest.cs
The fixed-width char mapping was setting up a value converter to implement the trailing-whitespace-truncating behavior of PostgreSQL. However, this needs to be done only if the CLR type of the mapping is a string; in cases where a value converter changes it to another type, the default comparer should be used.
Fixes #920
> Fix comparer of fixed-width char mapping when value converter is used

- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBitTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlVarbitTypeMapping.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
When working with BIT and VARBIT columns, BIT literals are generated incorrectly, because of excessive prefix.
Resolves #1256
> Fixed generation of BIT literal.

- src/EFCore.PG.NTS/Storage/Internal/NpgsqlNetTopologySuiteTypeMappingSourcePlugin.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
* Recognize ordinate-constrained spatial types (POINTZ, POINTMZ...)
* Recognize "geometry" as subtype, for SRID-constrained but for no particular subtype. (see #1267)
Fixes #1269
> Support more spatial types

- Directory.Build.targets
- src/EFCore.PG/Metadata/Conventions/NpgsqlConventionSetBuilder.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationStrategyConvention.cs
- test/EFCore.PG.FunctionalTests/CommandInterceptionNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/MigrationsInfrastructureNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindGroupByQueryNpgsqlTest.cs
* Convention change from EFCore 3574cfbddfdf485548b9e217f8e01a5ffeaf8562
* Unskipped command interception tests (dotnet/EFCore#16701)
* Un-overridden test (dotnet/EFCore#19855)
/cc @ajcvickers
> Sync to EF 5.0.0-preview.1.20107.7

- src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
`Normalized()` is not part of the `SpatialQueryTestBase`, so I had to be a little creative. I can try implementing those upstream if that's a better option.
> #457 :: Implemented translation for Geometry.Normalized()

- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
Got a "collection modified while enumerating" failure in the tests, probably because enums are being registered as the type mapping source is enumerating them. For all practical purposes this is a test-only fix.
> Fix concurrency issue in tests

- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlIndexExtensions.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
- test/EFCore.PG.Tests/Migrations/NpgsqlMigrationSqlGeneratorTest.cs
Support for index collation was added some time ago, using our own annotation. With collation support now integrated upstream, use that annotation instead.
> Switch to using the upstream collation annotation for indexes

- src/EFCore.PG/Extensions/NpgsqlModelBuilderExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlModelExtensions.cs
- src/EFCore.PG/Extensions/NpgsqlPropertyExtensions.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
Since PostgreSQL CREATE DATABASE is limited for collations (no ICU), this allows users to specify a collation on the model which propagates to column creation.
Part of #406
> Default column collations which propagate via EF

- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
This unblocks EF Core scaffolding for CockroachDB database. It's mainly about skipping failures for certain non-essential database objects which CockroachDB does not have (e.g. collations), and is generally useful to make our scaffolding more resilient.
/cc @rafiss
> Basic scaffolding for CockroachDB

- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
To avoid looking at pg_authid, which is a protected catalog table.
Fixes #1381
> Use namespace to filter out system collations

- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlHstoreTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Closes #1491
Replaces #1184
Note: this PR currently fails since the provider uses Npgsql 4.1, which doesn't yet have support for ImmutableDictionary (https://github.com/npgsql/npgsql/pull/2776). Once we take a dependency on a newer 5.0 preview everything should work.
/cc @Quogu
> Map hstore to ImmutableDictionary

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlByteArrayMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMathTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/MathQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindSelectQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs
We were pretty inconsistent with upper/lower case.
> Make all function translations lower-case

- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
fixes https://github.com/npgsql/efcore.pg/issues/1578
> Disable Multiplexing when checking if db exists, because we also disable Pooling

- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
> Take domain nullability into account when scaffolding

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
> Generate parentheses for PostgresBinaryExpression

- src/EFCore.PG/Extensions/PropertyInfoExtensions.cs
- src/EFCore.PG/Query/Expressions/Internal/PostgresArrayIndexExpression.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayArrayTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayListTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- src/EFCore.PG/Utilities/ReferenceNullabilityDecoder.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
Fixes #1683
/cc @maumar @smitpatel for the array case things turned out nice and simple - just override `ITypeMappingSource.FindMapping(IProperty)` to tweak the type mapping to contain the extra NRT information.
In theory, the same thing could be done for JSON to walk the POCO hierarchy and inject a tree nullability information into the type mapping... Will see if I feel like doing that :)
> Calculate array element nullability

- Directory.Packages.props
- test/EFCore.PG.FunctionalTests/DesignTimeNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsSharedTypeQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindSelectQueryNpgsqlTest.cs
Bumps `EFCoreVersion` from 6.0.0-preview.3.21158.1 to 6.0.0-preview.3.21163.3.
Bumps `MicrosoftExtensionsVersion` from 6.0.0-preview.3.21157.6 to 6.0.0-preview.3.21164.8.
Bumps `Npgsql` from 6.0.0-ci.20210303T093005+sha.cf73c6e0b to 6.0.0-ci.20210310T201503.
> Bump dependencies

- src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs
Removes the check for ExpressionType.Add around the DateTime + TimeSpan type mapping.
This case should allow both addition and subtraction, and this is already checked by the enclosing if.
Fixes #1777
> Fixes to DateTime arithmetics involving TimeSpan (#1777)

- src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Internal/NpgsqlOptions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs
- test/EFCore.PG.FunctionalTests/Query/CompatibilityQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlTestHelpers.cs
To not generate x = ANY(@array) construct.
Fixes #1794
> Add Redshift compatibility mode

- Directory.Build.props
- Directory.Packages.props
EFCore -> 6.0.0-preview.5.21216.1 (a1216b1de00f7443a38f8efe3387adfc5d7c21d0)
MicrosoftExtensions -> 6.0.0-preview.4.21211.7
Npgsql -> 6.0.0-ci.20210415T191850
> Bump dependencies for preview5 (#1810)

- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
Fixes #1812
This is a workaround; the root issue here is that NpgsqlRelationalConnection.CloneWith returns an instance with _connectionOwned=false, since the NpgsqlConnection is externally-provided. This means that disposing the NpgsqlRelationalConnection does not close/dispose the NpgsqlConnection, hence the leak.
Ideally CloneWith should return an instance with _connectionOwned=true.
> Fix connection leak in NpgsqlDatabaseCreator.Exists

- Directory.Build.props
- src/EFCore.PG.NTS/EFCore.PG.NTS.csproj
- src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj
- src/EFCore.PG/EFCore.PG.csproj
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Multitarget to net6.0
Closes #1781
Fixes #1865
Note that the translation tests are commented out, since they depend on upstream test support in EF Core, which doesn't have them yet (I'll work on this). I've verified locally that all the commented-out tests work.
> Support DateOnly/TimeOnly

- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- src/EFCore.PG/Utilities/ReferenceNullabilityDecoder.cs
Only check cases when the CLR type is actually an array or generic list.
Fixes #1839
> Fix array member nullability check

- src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlIndexBuilderExtensions.cs
- src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlModelBuilderExtensions.cs
- src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlPropertyBuilderExtensions.cs
- src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlIndexExtensions.cs
- src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlPropertyExtensions.cs
- src/EFCore.PG/Infrastructure/NpgsqlModelValidator.cs
- src/EFCore.PG/Metadata/NpgsqlValueGenerationStrategy.cs
- src/EFCore.PG/Metadata/NullSortOrder.cs
- src/EFCore.PG/Metadata/SortOrder.cs
- src/EFCore.PG/Utilities/SortOrderHelper.cs
- src/EFCore.PG/ValueGeneration/Internal/NpgsqlValueGeneratorSelector.cs
- test/EFCore.PG.FunctionalTests/Migrations/MigrationsInfrastructureNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
This reverts commit 926aa41ab9a9733a7ba18cf4aeb38c9cc20090b2.
Fixes #1879
> Revert "Move some public enums to Microsoft.EntityFrameworkCore.Metadata (#1669)"

- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayArrayTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayListTypeMapping.cs
Following https://github.com/dotnet/efcore/pull/25344
> Tweaks to array/list comparers

- src/EFCore.PG.NodaTime/Query/ExpressionTranslators/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
This adds a Translation for `TotalHours` of the `Duration` Type.
Maybe we should refactor this class and use `nameof` for all string constants.
Fixes #1933
> Add support for TotaHours and Duration

- Directory.Build.props
- Directory.Packages.props
- src/EFCore.PG.NTS/Infrastructure/Internal/NpgsqlNetTopologySuiteOptionsExtension.cs
- src/EFCore.PG.NodaTime/Infrastructure/Internal/NpgsqlNodaTimeOptionsExtension.cs
- src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlPropertyExtensions.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs
- src/EFCore.PG/Update/Internal/NpgsqlUpdateSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/NpgsqlValueGenerationScenariosTest.cs
- test/EFCore.PG.Tests/TestUtilities/FakeRelationalCommandDiagnosticsLogger.cs
- test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchFactoryTest.cs
- test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchTest.cs
Thanks @lauxjpn for upstream implementation in https://github.com/dotnet/efcore/pull/25178
Also bump dependencies to 6.0.0-rc.1.21406.1
> Enable value conversion support for identity/serial/hilo properties

- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
Note: the "default collation" is considered to be the collation of the `template1` database, which is what's used when a simple CREATE DATABASE is executed.
Fixes #1981
> Don't scaffold database collation when it's the default

- src/EFCore.PG.NodaTime/Storage/Internal/NodaTimeMappings.cs
- src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
Even in non-legacy mode, to support migrating old models which still require this mapping. Hopefully we'll be able to remove this in the future (https://github.com/dotnet/efcore/issues/26168)
/cc @vonzshik
> Bring back LegacyTimestampInstantMapping

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindJoinQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
- test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs
> Complete some pending test fixes for 6.0

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
> Bring back IS NULL parentheses hack

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs
Though until System.Text.Json supports DateOnly/TimeOnly, converters must be used.
Fixes #2148
> Don't block querying over DateOnly/TimeOnly in JSON

- src/EFCore.PG/Types/LTree.cs
`MatchesLQuery` is translated to the `~` operator.
> Fix typo in LTree documentation

- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/NpgsqlRetryingExecutionStrategy.cs
Allow specifying `errorCodesToAdd` without count or delay.
Fixes #2048.
> Add overload `EnableRetryOnFailure`.

- src/EFCore.PG/Query/Expressions/Internal/PostgresBinaryExpression.cs
fixes error Unhandled operator type combined with log in debug level
> Add missing LTree expression types in PostgresBinaryExpression

- src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
> Fix NodaTime Duration mapping

- .github/workflows/build.yml
- Directory.Packages.props
- global.json
- src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs
- src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatchFactory.cs
- test/Directory.Build.props
EF Core -> 7.0.0-preview.4.22176.1
Switched to dotnet sdk 7.0.100-preview.4.22175.5, because preview2 has an issue (https://github.com/dotnet/runtime/issues/66056)
> Sync dependencies

- src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
* Avoid time zone conversion when translating DateTime.Date with timestamptz.
* Return PG date from NodaTime {Local,Zoned}DateTime.Date
Fixes #2333
Fixes #2335
> Fix Date translations

- src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlDbFunctionsExtensions.cs
- src/EFCore.PG/Properties/NpgsqlStrings.Designer.cs
- src/EFCore.PG/Properties/NpgsqlStrings.resx
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRowValueComparisonTranslator.cs
- src/EFCore.PG/Query/Expressions/Internal/PostgresRowValueExpression.cs
- src/EFCore.PG/Query/Internal/NpgsqlEvaluatableExpressionFilter.cs
- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
- test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindAggregateOperatorsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/TPTGearsOfWarQueryNpgsqlTest.cs
This implements https://github.com/dotnet/efcore/issues/26822 for PostgreSQL only; things are easier here because there's already full support for arrays. I don't think this blocks us if we introduce something in relational, we can always obsolete the specific methods here.
Note: the methods have the long names (e.g. RowValueGreaterThan) since PG also supports array comparison in SQL.
/cc @smitpatel @ajcvickers @mrahhal
Closes #2349
> Support for row value comparisons

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRowValueTranslator.cs
- src/EFCore.PG/Query/Internal/NpgsqlEvaluatableExpressionFilter.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
As a nicer alternative to new ValueTuple<T1, T2>(...)
Continues #2349
/cc @mrahhal @smitpatel
> Translate ValueTuple.Create()

- Directory.Packages.props
- NuGet.config
- src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryTranslationPostprocessor.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryTranslationPostprocessorFactory.cs
- src/EFCore.PG/Query/Internal/NpgsqlSetOperationTypeResolutionCompensatingExpressionVisitor.cs
- src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
- src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs
- src/EFCore.PG/Update/Internal/NpgsqlUpdateSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/BatchingTest.cs
- test/EFCore.PG.FunctionalTests/ConnectionInterceptionNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindSetOperationsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/TPCFiltersInheritanceQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/Query/TPCFiltersInheritanceQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/TPCGearsOfWarQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/Query/TPCGearsOfWarQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/TPCInheritanceQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/Query/TPCInheritanceQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/TPCManyToManyNoTrackingQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/TPCManyToManyQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/Query/TPCManyToManyQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/TPCRelationshipsQueryNpgsqlTest.cs
- test/EFCore.PG.Tests/TestUtilities/FakeRelationalCommandDiagnosticsLogger.cs
- test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchFactoryTest.cs
- test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchTest.cs
And fix nested set operations with leftmost nulls
Fixes #2366
> Sync EF Core to 7.0.0-preview.5.22260.3

- src/EFCore.PG.NTS/Extensions/NpgsqlNetTopologySuiteServiceCollectionExtensions.cs
- src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
- src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
> Translate spatial aggregates

- src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
- src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlAggregateDbFunctionsExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlAggregateMethodCallTranslatorProvider.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMiscAggregateMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlQueryableAggregateMethodTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStatisticsAggregateMethodTranslator.cs
- src/EFCore.PG/Query/Expressions/Internal/PostgresFunctionExpression.cs
- src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
- test/EFCore.PG.FunctionalTests/Query/MultirangeQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindGroupByQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs
Here's some nice WIP based off of @smitpatel's great work in https://github.com/dotnet/efcore/pull/28092.
This implements the PG-specific aggregate operators ([FILTER](https://github.com/npgsql/efcore.pg/pull/2383/files#diff-93dee472cc58de12f790841bc6d992751b2af17d1fa3d7be5a3165bdbbb1aaa7R2465) and [ORDER BY](https://github.com/npgsql/efcore.pg/pull/2383/files#diff-93dee472cc58de12f790841bc6d992751b2af17d1fa3d7be5a3165bdbbb1aaa7R3158)), and provides a first implementation of [string_agg](https://github.com/npgsql/efcore.pg/pull/2383/files#diff-93dee472cc58de12f790841bc6d992751b2af17d1fa3d7be5a3165bdbbb1aaa7R3177) and [array_agg](https://github.com/npgsql/efcore.pg/pull/2383/files#diff-93dee472cc58de12f790841bc6d992751b2af17d1fa3d7be5a3165bdbbb1aaa7R3188). Really impressive we can do this! …
> Translate PostgreSQL custom aggregates

- src/EFCore.PG.NodaTime/Extensions/NpgsqlNodaTimeDbFunctionsExtensions.cs
- src/EFCore.PG.NodaTime/Extensions/NpgsqlNodaTimeServiceCollectionExtensions.cs
- src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeAggregateMethodCallTranslatorPlugin.cs
- src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlAggregateDbFunctionsExtensions.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMiscAggregateMethodTranslator.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs
- test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindGroupByQueryNpgsqlTest.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
> Implement sum and average over TimeSpan

- Directory.Build.props
- Directory.Packages.props
- src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs
- src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlModelBuilderExtensions.cs
- src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlPropertyBuilderExtensions.cs
- src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlModelExtensions.cs
- src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlPropertyExtensions.cs
- src/EFCore.PG/Infrastructure/NpgsqlModelValidator.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlConventionSetBuilder.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlStoreGenerationConvention.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationConvention.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationStrategyConvention.cs
- src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs
- src/EFCore.PG/Metadata/NpgsqlValueGenerationStrategy.cs
- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- src/EFCore.PG/Update/Internal/NpgsqlUpdateSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryFixture.cs
- test/EFCore.PG.FunctionalTests/Query/BigIntegerQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/FunkyDataQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/Query/TPCGearsOfWarQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/Query/TPTGearsOfWarQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs
- test/EFCore.PG.FunctionalTests/TwoDatabasesNpgsqlTest.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
And sync EF Core to 7.0.0-rc.1.22378.4.
Closes #2444
Closes #2445
> Sequence-based value generation, by default for TPC keys

- Directory.Packages.props
- src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs
- src/EFCore.PG/Query/Expressions/Internal/PostgresDeleteExpression.cs
- src/EFCore.PG/Query/Internal/NonQueryConvertingExpressionVisitor.cs
- src/EFCore.PG/Query/Internal/NpgsqlParameterBasedSqlProcessor.cs
- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitorFactory.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlTestHelpers.cs
Synced against https://github.com/dotnet/efcore/pull/28492.
Nothing much to see here yet, the tests are implemented and all pass (see last commit only). The PostgreSQL-specific USING syntax for joining needs to be implemented, will do that following upstream implementation for SQL Server.
Closes #2450
/cc @smitpatel
> Implement ExecuteDelete

- Directory.Packages.props
- src/EFCore.PG/Query/Internal/NpgsqlDeleteConvertingExpressionVisitor.cs
- src/EFCore.PG/Query/Internal/NpgsqlParameterBasedSqlProcessor.cs
- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/TableSplittingNpgsqlTest.cs
Here's the PG-side PR, nothing much to see here. Unlike with delete I don't think I'll need a special PG expression since the relational thing works pretty well as-is (no special logic needed for USING in DELETE). Will sync this as you make progress in [#28626](https://github.com/dotnet/efcore/pull/28626/files#).
Closes #2450
> Implement ExecuteUpdate

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlLTreeTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/LTreeQueryTest.cs
> Correct LTree type mapping logic

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/Ef6GroupByNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/EntitySplittingQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/NetworkQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindGroupByQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindSetOperationsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs
- test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
(leaving the one on the EF side)
Closes #2105
> Remove IS NULL parentheses hack

- src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NullSemanticsQueryNpgsqlTest.cs
> Null semantics for row value equality

- src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlEntityTypeBuilderExtensions.cs
- src/EFCore.PG/Metadata/Conventions/NpgsqlPostgresModelFinalizingConvention.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/DatabindingNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/F1NpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/OptimisticConcurrencyNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/SerializationNpgsqlTest.cs
* Support value-converted concurrency tokens
* Obsolete UseXminAsConcurrencyToken
* Improve testing and align with upstream
Continues #2543
> Fixup to xmin/concurrency token changes

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesNpgsqlTest.cs
> Fix ExecuteUpdate with invalid reference to main table

- src/EFCore.PG/Query/Expressions/Internal/PostgresRowValueExpression.cs
Because 'i' is iterator of previous cycle
> Fix cycle iterator name for PostgresRowValueExpression.VisitChildren

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
Mainly concatenate constant patterns in translation instead of generation SQL concat; also use ~* for case-insensitivity, and some test cleanup.
> Minor regex improvements

- src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
- test/EFCore.PG.Tests/NpgsqlRelationalConnectionTest.cs
> Fix prepared transactions caused by case sensitive string comparison (#2624)

- src/EFCore.PG/Infrastructure/Internal/INpgsqlSingletonOptions.cs
- src/EFCore.PG/Internal/NpgsqlSingletonOptions.cs
- src/EFCore.PG/Properties/NpgsqlStrings.Designer.cs
- src/EFCore.PG/Properties/NpgsqlStrings.resx
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
> Fix enum mapping when using NpgsqlDataSource

- src/EFCore.PG/Migrations/Internal/NpgsqlHistoryRepository.cs
- test/EFCore.PG.Tests/Migrations/NpgsqlHistoryRepositoryTest.cs
> Fix migration history table lookup

- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
Ran into this config problem a couple days ago. 
Using the npgsql data source builder to configure a enum mapping and providing a certificate callback not using this very same data source builder throws an exception with a default message. Which may be confusing.
> Provide a better exception message for invalid data source config.

- src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
> Translate DateTime.TimeOfDay and NodaTime LocalDateTime.Time

- .github/workflows/build.yml
Since it's not supported anymore
> Stop running ci tests against pg 10

- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
This is a regression that was introduced in afe8200cb7cd1b6780928aa7cfd05cc2da16c0bd but no test was covering the parsing of precision and scale.
Note: I discovered this bug while scaffolding the Chinook database with my [new tool](https://github.com/0xced/EFCore.Scaffolding#sample-code). The columns defined with `numeric(10,2)` would not be scaffolded with these warnings:
> Could not find type mapping for column 'public.Track.UnitPrice' with data type 'numeric(10,2)'. Skipping column.
> Could not find type mapping for column 'public.Invoice.Total' with data type 'numeric(10,2)'. Skipping column.
> Could not find type mapping for column 'public.InvoiceLine.UnitPrice' with data type 'numeric(10,2)'. Skipping column.
I'm pretty happy it only took me only about one hour from noticing the …
> Fix parsing of store types precision and scale

- test/EFCore.PG.FunctionalTests/Query/NorthwindQueryNpgsqlFixture.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlNorthwindTestStoreFactory.cs
Make sure the (legacy) Northwind data source always gets created with support for dynamic JSON and records as tuples.
> Fix test concurrency issue

- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
> Change scaffolding PG arrays to List<T> instead of T[]

- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/DefaultValuesTest.cs
- test/EFCore.PG.FunctionalTests/Migrations/MigrationsInfrastructureNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/SpatialNpgsqlFixture.cs
> Raise default PG compat version to 14

- src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
> Parse bool and integer types in scaffolding

- src/EFCore.PG/Design/Internal/NpgsqlCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlStringTypeMapping.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlULongTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
> Support a few more type mappings in the compiled model

- src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
- src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
- test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlDatabaseCleaner.cs
> Fix containment inference of multirange mapping from non-range item

- src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs
- test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
> Cast NodaTime DateInterval.End to date.

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Migrations/NpgsqlMigrationsSqlGeneratorTest.cs
> Fix index creation when both collation and operators are specified

- src/EFCore.PG/Query/Expressions/Internal/PgTableValuedFunctionExpression.cs
> Fix PgTableValuedFunctionExpression cloning

- src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs
> Fix bad array access when an AFTER trigger raises an exception in SaveChanges

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/TrigramsQueryNpgsqlTest.cs
> Always add parentheses around PgUnknownBinaryExpression

- src/EFCore.PG/Extensions/ExpressionVisitorExtensions.cs
- src/EFCore.PG/Query/Expressions/Internal/PgTableValuedFunctionExpression.cs
- src/EFCore.PG/Query/Expressions/Internal/PgUnnestExpression.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryTranslationPostprocessor.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTreePruner.cs
- src/EFCore.PG/Query/Internal/NpgsqlUnnestPostprocessor.cs
- test/EFCore.PG.FunctionalTests/Query/JsonQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs
> Prune PgTableValuedFunctionExpression's projection

- Directory.Packages.props
- test/EFCore.PG.FunctionalTests/ModelBuilding/NpgsqlModelBuilderGenericTest.cs
See https://github.com/dotnet/efcore/issues/33059
> Downgrade xunit back to 2.6.1

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryFixture.cs
- test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
- test/EFCore.PG.FunctionalTests/TestModels/Array/ArrayEntity.cs
- test/EFCore.PG.FunctionalTests/TestModels/Array/ArrayQueryContext.cs
- test/EFCore.PG.FunctionalTests/TestModels/Array/ArrayQueryData.cs
Not sure if I got everything right about this, but I hope it fixes #3105 :)
> Add translation of string.Join overload used with List<string> parameter, fix #3105

- src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlDbFunctionsExtensions.cs
> ToDate/ToTimestamp non-nullable

- src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlPropertyBuilderExtensions.cs
- src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlPropertyExtensions.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlModelValidator.cs
- test/EFCore.PG.Tests/Metadata/NpgsqlMetadataBuilderExtensionsTest.cs
Ports over https://github.com/dotnet/efcore/pull/33457/files
Closes #3141
> Stop eagerly throwing when setting value generation strategy

- src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitor.cs
> Add missing check for predicate in primitive collection simplifications

- src/EFCore.PG/Extensions/Internal/NpgsqlShapedQueryExpressionExtensions.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.PG/Query/Internal/NpgsqlUnnestPostprocessor.cs
- test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs
> Add ordering by ordinality column for primitive collections

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs
- src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
> Correct non-NodaTime date/time type mappings when NodaTime is configured

- src/EFCore.PG/ValueGeneration/Internal/NpgsqlValueGeneratorSelector.cs
- src/EFCore.PG/ValueGeneration/NpgsqlSequentialGuidValueGenerator.cs
- test/EFCore.PG.Tests/NpgsqlValueGeneratorSelectorTest.cs
EF only automatically configured client-side GUID generation for **key** GUID properties; other non-key GUID properties do not get configured by default. Since users may want to explicitly configure that behavior (see explicit call-out on this [in the docs](https://www.npgsql.org/efcore/modeling/generated-properties.html#guiduuid-generation)), the new UUID7 generator should be public and more properly named.
@ChrisJollyAU @Timovzl does this (and the new naming) make sense to you?
Follow-up to #3249
> Rename NpgsqlUuid7ValueGenerator to NpgsqlSequentialGuidValueGenerator and make it public

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesNpgsqlTest.cs
> Don't use same table in join when it is also primary target table

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindDbFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs
> Negated syntax for regex and ILIKE

- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
- src/EFCore.PG/Properties/NpgsqlStrings.Designer.cs
- src/EFCore.PG/Properties/NpgsqlStrings.resx
- src/EFCore.PG/Storage/Internal/NpgsqlDataSourceManager.cs
- test/EFCore.PG.FunctionalTests/LoggingNpgsqlTest.cs
- test/EFCore.PG.Tests/NpgsqlRelationalConnectionTest.cs
Closes #2542
Closes #2704
/cc @NinoFloris
> Add ConfigureDataSource() to NpgsqlDbContextOptionsBuilder

- src/EFCore.PG/Query/Expressions/Internal/PgAnyExpression.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryCompilationContext.cs
- src/EFCore.PG/Query/Internal/NpgsqlQueryCompilationContextFactory.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- test/EFCore.PG.FunctionalTests/NpgsqlComplianceTest.cs
- test/EFCore.PG.FunctionalTests/Query/AdHocPrecompiledQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/PrecompiledQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/PrecompiledSqlPregenerationQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlPrecompiledQueryTestHelpers.cs
- Enable support for precompiled queries
- Adds the precompiled query tests in
Most work except for a few exceptions: Concat, Except,Intersect,Union
Looks like we need to find a way to add a reference to `Npgsql` when its doing the compilation as the error is of the style: `The type 'NpgsqlTsVector' is defined in an assembly that is not referenced. You must add a reference to assembly 'Npgsql, Version=8.0.3.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.` 
Contributes to #3257
> Implement Precompiled Query Tests

- src/EFCore.PG/Migrations/Internal/NpgsqlHistoryRepository.cs
> Catch exception instead of trying to check if the history repository exists

- src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
> Properly escape constant regex patterns

- src/EFCore.PG.NTS/Storage/Internal/NpgsqlJsonGeometryWktReaderWriter.cs
- test/EFCore.PG.FunctionalTests/JsonTypesNpgsqlTest.cs
> Prefix JSON geometry representation with SRID

- src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindAggregateOperatorsQueryNpgsqlTest.cs
- test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs
> Translate array.Where(i => i != x) to array_remove

- src/EFCore.PG/Migrations/Internal/NpgsqlHistoryRepository.cs
> Remove enum/extension conventions when creating migrations history table

- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
- src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs
- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
- test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs
* Translate DateOnly.DayNumber -> `x - DATE '0001-01-01'
* Translate DateOnly.FromDayNumber -> `DATE '0001-01-01' + x`
* Optimize translation of (x - c) - (y - c) to x - y
Closes #3194
> Translations around DateOnly.DayNumber

- Directory.Packages.props
- src/EFCore.PG/Storage/Internal/INpgsqlRelationalConnection.cs
- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
- src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
> Call NpgsqlDataSource.Clear when doing EnsureDeleted

- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
- test/EFCore.PG.FunctionalTests/NpgsqlDatabaseCreatorTest.cs
> Invoke connection interceptor before tweaking connection string in Exists()

- src/EFCore.PG/Design/Internal/NpgsqlCSharpRuntimeAnnotationCodeGenerator.cs
> Detect and throw for NpgsqlTypeMappings as element type mappings

- src/EFCore.PG/Infrastructure/Internal/EnumDefinition.cs
- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
- src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs
> Allow MapEnum() without an enum name

- src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
- test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
> Add NullIf Translation for Ternary expressions

- src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
- test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
To better handling reordering scenarios.
Fixes #3424
> Redo enum label addition

- src/EFCore.PG/ValueGeneration/Internal/NpgsqlValueGeneratorSelector.cs
- src/EFCore.PG/ValueGeneration/NpgsqlSequentialStringValueGenerator.cs
- test/EFCore.PG.Tests/NpgsqlValueGeneratorSelectorTest.cs
> Generate UUIDv7 values for value-generated strings

- src/EFCore.PG/Migrations/Internal/NpgsqlMigrator.cs
Closes #3464
Branch is derived from hotix/9.0.4
If not wanted there, it could probably be cherry picked elsewhere.
> Always close connection after reloading types in migration.

- src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
> Preserve ConfigureDataSource() callback when applying other context options

- src/EFCore.PG/Storage/ValueConversion/NpgsqlArrayConverter.cs
> Make NpgsqlArrayConverter not throw for struct arrays

- src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
Always close connection after types was reloaded.
Fixes #3560
> Reload types should close the newly opened connection.
