npgsql/efcore.pg

src/Npgsql.EntityFrameworkCore.PostgreSQL.Design/Npgsql.EntityFrameworkCore.PostgreSQL.Design.csproj, src/Npgsql.EntityFrameworkCore.PostgreSQL/Npgsql.EntityFrameworkCore.PostgreSQL.csproj, test/Npgsql.EntityFrameworkCore.PostgreSQL.FunctionalTests/Npgsql.EntityFrameworkCore.PostgreSQL.FunctionalTests.csproj, test/Npgsql.EntityFrameworkCore.PostgreSQL.Tests/Npgsql.EntityFrameworkCore.PostgreSQL.Tests.csproj
=> NpgSql Updated from 3.2.0 to 3.2.1

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringContainsTranslator.cs
Simple fix for #384 that adds a cast to `citext` for the argument of `Contains()` if the object has the store type `citext` (similar to 9f8cd0cb0e31953a6cd1e704642d45a6bbe12560).
=> Fixes #384 via conditional argument cast to citext

doc/index.md
=> Docs: remove reference to Npgsql.EntityFrameworkCore.Design

doc/release-notes/2.0.md
Updates the 2.0 Release Notes to contain a link to nuget.
=> Updated the docs to contain a link to nuget

doc/index.md
=> Updating for 2.1, modernizing the examples

test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
Skips:
```
Npgsql.EntityFrameworkCore
.PostgreSQL
.MigrationsNpgsqlTest
.Can_apply_all_migrations_async()
```
https://ci.appveyor.com/project/roji/npgsql-entityframeworkcore-postgresql/build/2.2.0-514
=> Skip a flaky test in MigrationsNpgsqlTest

README.md
Updates to include NuGet, MyGet, and Gitter badges to align with the driver repository.
=> Adds badges to the readme

test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
- Adds tests to demonstrate the behavior of mapped and unmapped enums.
- Adds a test to document an unsupported cast on an unmapped enum.
Related: #489
=> Adds tests to verify enum behavior when un/mapped

src/EFCore.PG/Infrastructure/Internal/INpgsqlOptions.cs, src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs, src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs, src/EFCore.PG/Internal/NpgsqlOptions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlCompositeMethodCallTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateAddTranslator.cs, src/EFCore.PG/Query/Expressions/Internal/PgFunctionExpression.cs, test/EFCore.PG.FunctionalTests/Query/CompatibilityQueryNpgsqlTest.cs
=> Add doc comments and refactor PgFunctionExpression

src/EFCore.PG/Extensions/NpgsqlRangeExtensions.cs
Also adds xml docs to highlight these are throw-always methods.
=> Update range extensions to throw a message

src/EFCore.PG/Query/ExpressionVisitors/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Null operand passed to ArrayAnyAllExpression

doc/mapping/range.md
=> Update range operator docs

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs, src/EFCore.PG/Query/Expressions/Internal/AtTimeZoneExpression.cs
=> Update AtTimeZoneExpression for use in the NodaTime plugin

.appveyor.yml, .travis.yml
=> Update CI scripts to run functional plugin tests

src/EFCore.PG/Scaffolding/Internal/NpgsqlCodeGenerator.cs
=> Add doc comments to NpgsqlCodeGenerator

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
=> Refactor and document NpgsqlDatabaseModelFactory (1)

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- Part of #597
- Based on #599
=>  Refactor and document NpgsqlDatabaseModelFactory (2)

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- Part of #597
- Based on #600
=> Refactor and document NpgsqlDatabaseModelFactory (3)

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
- Part of #597
- Based on #601
=> Refactor and document NpgsqlDatabaseModelFactory (4)

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBitTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBoolTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlByteArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCitextTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlGeometricTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlHstoreTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonbTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlListTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlNetworkTypeMappings.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRegconfigTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlStringTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTidTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTsQueryTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTsRankingNormalizationTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTsVectorMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlUIntTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlVarbitTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlXmlTypeMapping.cs
This PR depends on #608.
Reacting to aspnet/EntityFrameworkCore#11978
See #416
=> Simplify type mapping clone methods

doc/mapping/range.md
Change per review comment: https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/675#pullrequestreview-167073611
=> Use generic `MapRange` in docs

Directory.Build.props, NuGet.config, src/EFCore.PG.NTS/Design/Internal/NpgsqlNetTopologySuiteDesignTimeServices.cs, src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs, src/EFCore.PG.NTS/Scaffolding/Internal/NpgsqlNetTopologySuiteCodeGeneratorPlugin.cs, src/EFCore.PG.NTS/Storage/Internal/NpgsqlGeometryTypeMapping.cs, src/EFCore.PG.NodaTime/Design/Internal/NpgsqlNodaTimeDesignTimeServices.cs, src/EFCore.PG.NodaTime/Scaffolding/Internal/NpgsqlNodaTimeCodeGeneratorPlugin.cs, src/EFCore.PG/Design/Internal/NpgsqlDesignTimeServices.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlCodeGenerator.cs, src/EFCore.PG/Utilities/Check.cs, src/Shared/Check.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs, test/EFCore.PG.FunctionalTests/StoreGeneratedNpgsqlTest.cs, test/EFCore.PG.Tests/Scaffolding/NpgsqlCodeGeneratorTest.cs
=> Scaffold plugin options

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlEnumTypeMapping.cs, test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
=> Prefer `PgNameAttribute` in `NpgsqlEnumTypeMapping`

src/EFCore.PG/Metadata/INpgsqlPropertyAnnotations.cs, src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs
Per the [discussion](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/718#issuecomment-441069992) after #718, simplifying the annotation provider and adding some nullability annotations.
=> Simplify annotation provider (from 718)

doc/mapping/nts.md
=> Add docs on constraining spatial columns

src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, src/EFCore.PG/Infrastructure/NpgsqlModelValidator.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Replace ModelValidator and validate identity columns

.editorconfig, EFCore.PG.sln.DotSettings
Per discussion, updated with my local dictionary words.
=> Update `.DotSettings` with dictionary words

EFCore.PG.sln.DotSettings, test/EFCore.PG.Tests/Metadata/NpgsqlInternalMetadataBuilderExtensionsTest.cs, test/EFCore.PG.Tests/Metadata/NpgsqlMetadataExtensionsTest.cs, test/EFCore.PG.Tests/NpgsqlDatabaseFacadeTest.cs, test/EFCore.PG.Tests/NpgsqlValueGeneratorSelectorTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs, test/EFCore.PG.Tests/TestUtilities/FakeInterceptingLogger.cs
Continuing the work in #780 for `EFCore.PG.Tests`.
=> Cleanup unit test warnings

src/EFCore.PG/Design/Internal/NpgsqlDesignTimeServices.cs, src/EFCore.PG/Diagnostics/NpgsqlEventId.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBitTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlHstoreTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlListTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlNetworkTypeMappings.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTypeMapping.cs, src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs
=> Add xmldocs for various public members

test/EFCore.PG.Plugins.FunctionalTests/NodaTimeQueryNpgsqlTest.cs, test/EFCore.PG.Plugins.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
Continuing the work in #780 for `EFCore.PG.Plugins.FunctionalTests`.
=> Cleanup plugin test warnings

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs
_Backport of #787. Opening PR for CI tests. Planning to merge on pass._
=> Format date/time literals using invariant culture (#788)

EFCore.PG.sln.DotSettings, src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs, src/EFCore.PG/Metadata/INpgsqlEntityTypeAnnotations.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs, src/EFCore.PG/Metadata/NpgsqlEntityTypeAnnotations.cs, src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
=> Add support for unlogged tables

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateAddTranslator.cs
=> Used invariant culture to generate interval expressions

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterTypeMapping.cs, test/EFCore.PG.FunctionalTests/Query/CharacterQueryNpgsqlTest.cs
=> Update `character` comparer with expression tree

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Refactor create table methods (reacting)

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
Also fix bug in system table exclusion
Closes #878
=> Reverse-engineer views

.appveyor.yml
Just opening to trigger the build, plan to merge on clean build.
=> Update PostGIS version for AppVeyor

.appveyor.yml, .build/setup_appveyor.ps1, .build/setup_postgres.ps1, .build/setup_postgres.sh, Directory.Build.props, azure-pipelines.yml, src/EFCore.PG.NTS/EFCore.PG.NTS.csproj, test/Directory.Build.props
Opening against `hotfix/2.1.4` for discussion.
=> Re-target hotfix/2.1.4 as hotfix/2.1.11

.appveyor.yml, .build/setup_appveyor.ps1, .build/setup_postgres.ps1, .build/setup_postgres.sh, Directory.Build.props, azure-pipelines.yml, src/EFCore.PG.NTS/EFCore.PG.NTS.csproj, test/Directory.Build.props, test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj
Opening against `hotfix/2.2.5` for discussion.
=> Re-target hotfix/2.2.5 as hotfix/2.2.6

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
=> Fix scaffolding of serial columns in non-public schemas

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
Fixes #921 by applying changes from #701.
Tried to cherry-pick 266aa00279c88c8e568a48e5936bfb962f21ced7, conflicts needed to be fixed.
_reopened from #923_
=> Add semicolon and condition for schema statement to 2.1.11

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlModelBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlModelExtensions.cs, src/EFCore.PG/Extensions/NpgsqlPropertyBuilderExtensions.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlStoreGenerationConvention.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationStrategyConvention.cs, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/F1NpgsqlFixture.cs, test/EFCore.PG.FunctionalTests/MonsterFixupChangedChangingNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/NpgsqlValueGenerationScenariosTest.cs, test/EFCore.PG.FunctionalTests/ProxyGraphUpdatesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/StoreGeneratedNpgsqlTest.cs, test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs, test/EFCore.PG.Tests/Metadata/Conventions/NpgsqlValueGenerationStrategyConventionTest.cs, test/EFCore.PG.Tests/Metadata/NpgsqlBuilderExtensionsTest.cs, test/EFCore.PG.Tests/Metadata/NpgsqlMetadataBuilderExtensionsTest.cs, test/EFCore.PG.Tests/NpgsqlValueGeneratorSelectorTest.cs
Closes #942
Follows https://github.com/aspnet/EntityFrameworkCore/issues/16686
/cc @ajcvickers
=> Remove provider prefix from builder metadata extension method

src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs, src/EFCore.PG/Query/Internal/NpgsqlCompiledQueryCacheKeyGenerator.cs
Follows https://github.com/aspnet/EntityFrameworkCore/pull/16069
/cc @YohDeadfall just in case you haven't used the new HashCode yet :)
=> Use new BCL HashCode class

test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
Following https://github.com/aspnet/EntityFrameworkCore/pull/16816
=> Clean up migration test SQL assertions

src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlIndexExtensions.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs, src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
=> Add support for creating indexes concurrently

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs, src/EFCore.PG/Query/Expressions/Internal/JsonTraversalExpression.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonObjectTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj, test/EFCore.PG.FunctionalTests/Query/JsonQueryTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> JSON support

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Fix migrating serial to identity with schema

src/EFCore.PG/Query/Sql/Internal/NpgsqlQuerySqlGenerator.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fix length check on empty arrays

src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
=> Pass the original options with modified connectionstring/DbConnection

doc/mapping/array.md, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonQueryTest.cs
=> Fixed incorrect logic of Any method translation

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs
PG returns different types for Sum, so apply conversions.
Closes #976
=> More precise translation of Sum

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonObjectTypeMapping.cs, test/EFCore.PG.FunctionalTests/Query/JsonQueryTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> Fix JSON literal generation

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
In #819 we changed scaffolding to look at the pg_sequence catalog table instead of information_schema.sequences, but the former is only available starting with PG 10. Switched back to using information_schema and verified that scaffolding is fully compatible with PG 9.6.
Fixes #1001
=> Fix sequence scaffolding for old PG

test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs, test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlDatabaseCleaner.cs
=> Clean up user-defined function tests

src/EFCore.PG/Query/Internal/NpgsqlSqlExpressionFactory.cs, test/EFCore.PG.Plugins.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
=> Special inference logic for TimeSpan/Period

doc/release-notes/3.0.md, src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, src/EFCore.PG/Storage/ValueConversion/NpgsqlArrayConverter.cs, src/EFCore.PG/Storage/ValueConversion/NpgsqlValueConverterSelector.cs, test/EFCore.PG.Tests/Storage/NpgsqlArrayValueConverterTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlValueConverterSelectorTest.cs
Closes #1031
(sometimes you just have to sit down and code a cute feature)
=> Array value converters

src/EFCore.PG/Extensions/NpgsqlIndexExtensions.cs
=> Fix index operator metadata methods

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonDomTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
This addressed all the PR comments from https://github.com/npgsql/efcore.pg/pull/1087, which ended up simplying the changes a lot.
Fixes #1086.
=> Updated JSON GetGuid to use CAST

src/EFCore.PG.NodaTime/Storage/Internal/NodaTimeMappings.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBitTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlGeometricTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlNetworkTypeMappings.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTidTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlVarbitTypeMapping.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Extracted cached MethodInfos and renamed.
Split out from #1102
=> Code literal generation cleanup

src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
=> Clean up database existence checks

test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/ComputedColumnTest.cs, test/EFCore.PG.FunctionalTests/ConnectionSpecificationTest.cs, test/EFCore.PG.FunctionalTests/DefaultValuesTest.cs, test/EFCore.PG.FunctionalTests/ExecutionStrategyTest.cs, test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs, test/EFCore.PG.FunctionalTests/NpgsqlValueGenerationScenariosTest.cs, test/EFCore.PG.FunctionalTests/OptimisticConcurrencyNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/CharacterQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/DbFunctionsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonStringQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/MathQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/NavigationTest.cs, test/EFCore.PG.FunctionalTests/Query/NetworkQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/QueryBugTest.cs, test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/SystemColumnTest.cs, test/EFCore.PG.FunctionalTests/UpdatesNpgsqlTest.cs
Did the simple/obvious cases, others remain but let's handle them later.
=> Using declarations in tests

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
=> Translate parameterized Contains to PG = ANY ()

Directory.Build.targets, NuGet.Config, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayMethodTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlNetworkTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlJsonTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs, src/EFCore.PG/ValueGeneration/Internal/NpgsqlSequenceHiLoValueGenerator.cs, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsWeakQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/GroupByQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonStringQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/QueryNoClientEvalNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.Functions.cs, test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.ResultOperators.cs, test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> Code literal generation for JsonElement

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
=> Fix nullable handling within JSON

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonDbFunctionsTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
=> Fix type mappings for JSON containment functions

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlObjectToStringTranslator.cs, test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs
=> Translate ToString on enums

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/FunkyDataQueryNpgsqlTest.cs
=> Fix {Starts,Ends}With and support citext properly

src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
=> Fixes to array facet type mapping handling

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
This reverts commit f9e62e522284aea5acfb0b8f3111b852499f2157.
Fixes #1154
=> Revert "Use PERFORM within PL/pgSQL block to discard result (#1092)"

src/EFCore.PG/Query/Internal/NpgsqlSqlExpressionFactory.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
* Recognize timestamp subtraction in type inference
* Some cleanup around addition/subtraction with interval
Fixes #1179
=> Fix some date/time type inference logic

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/NpgsqlMigrationSqlGeneratorTest.cs
=> Support for adding enum values

src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs
=> Index IsCreatedConcurrently is true by default

src/EFCore.PG/Extensions/VersionExtensions.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Fix adding enum labels on PG < 12

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
Depends on PR #1234 (see only last commit)
=> Translate bytea length

test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindAggregateOperatorsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindGroupByQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindSelectQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
To align with EF Core conventions.
=> Rename async param in tests

.github/workflows/build.yml
Following https://github.com/npgsql/npgsql/pull/2823
* Extract dotnet SDK version to an environment variable
* PostGIS version is now an environment variable instead of a matrix parameter.
* Remove SHA1 from artifact name
=> Minor Github Actions changes

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlNetworkTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
=> Use Not instead of Negate for network/fulltext

test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
When restarting a sequence's value, PG still reports the original start value when scaffolding - this broke the test.
Fixes #1218
=> Fix alter sequence test (start value)

EFCore.PG.sln.DotSettings, src/EFCore.PG.NodaTime/Query/ExpressionTranslators/Internal/NpgsqlNodaTimeMethodCallTranslatorPlugin.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlByteArrayMethodTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs, src/EFCore.PG/Query/Expressions/Internal/PgFunctionExpression.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
=> Implement Contains over bytea

Directory.Build.props, src/Directory.Build.props
=> Include git branch and commit in nuspec

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlIndexExtensions.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs, src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
Hi. I would like to suggest you new feature to create a table index on 'tsvector' based on multiple columns. We discussed about it in #1097.
=> Add possibility to create table index on tsvector

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, src/EFCore.PG/Extensions/NpgsqlEntityTypeBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlIndexBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlIndexExtensions.cs, src/EFCore.PG/Extensions/NpgsqlPropertyBuilderExtensions.cs, src/EFCore.PG/Extensions/NpgsqlPropertyExtensions.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs, src/EFCore.PG/Migrations/Internal/NpgsqlMigrationsAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
Make the expression index and generated column implementations more consistent etc.
See #1181 and #1262
/cc @artfulsage if you think any of the changes are bad or could be improved, don't hesitate to let me know.
=> Some cleanup around tsvector

src/EFCore.PG.NodaTime/Storage/Internal/NodaTimeMappings.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
=> Code literal support for NodaTime Instant and ZonedDateTime

Directory.Build.targets, src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitorFactory.cs, src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs, test/EFCore.PG.FunctionalTests/CustomConvertersNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/GraphUpdates/GraphUpdatesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/GraphUpdates/ProxyGraphUpdatesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindDbFunctionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs, test/EFCore.PG.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs, test/EFCore.PG.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
Sync to EF 5.0.0-preview.3.20177.3, commit 87714065027c161e29d8b5901813a07682e93538
This includes the new relational model changes (/cc @AndriySvyryd @ajcvickers in case you are interested).
=> Sync to 5.0.0-preview.3.20177.3

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
=> Avoid using PostgreSQL "char" in scaffolding

src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationConvention.cs
=> Configure TsVector columns as OnAddOrUpdate

src/EFCore.PG/Extensions/NpgsqlPropertyExtensions.cs
=> Fix value generation on owned entity keys

src/EFCore.PG/ValueGeneration/Internal/NpgsqlValueGeneratorCache.cs, test/EFCore.PG.FunctionalTests/SequenceEndToEndTest.cs
Fixes #1394
Note: this is a port of https://github.com/dotnet/efcore/pull/14330 for EFCore.PG
=> Fix HiLo across multiple databases

src/EFCore.PG/Query/Internal/NpgsqlEvaluatableExpressionFilter.cs
=> Fix logic bug in NpgsqlEvaluatableExpressionFilter

src/EFCore.PG.NodaTime/Design/Internal/NpgsqlNodaTimeDesignTimeServices.cs, src/EFCore.PG.NodaTime/Extensions/NpgsqlNodaTimeServiceCollectionExtensions.cs, src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeEvaluatableExpressionFilterPlugin.cs, src/EFCore.PG/Query/Internal/NpgsqlEvaluatableExpressionFilter.cs
=> Move NodaTime evaluatable definitions out to the plugin

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonDomTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
=> Fix nullable Guid behavior in jsonb

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonDomTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlExpressionFactory.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs
=> Fix JSON operations directly on the root (column)

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
=> Respect [JsonPropertyName] in query translation

src/EFCore.PG/Query/Internal/NpgsqlSqlExpressionFactory.cs
=> Fix inference for ILikeExpression without escape char

src/Directory.Build.props
Fix transfer of PR https://github.com/npgsql/npgsql/pull/3078#issuecomment-662547534, fixing https://github.com/npgsql/npgsql/issues/3063
/cc @roji
=> Fix SourceLink and Deterministic fields in nuget packages

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlMoneyTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindAggregateOperatorsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindQueryNpgsqlFixture.cs
=> Fix mapping of PG money

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMathTranslator.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDoubleTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlFloatTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
* Literal generation for NaN, positive/negative infinity
* Method translation for double.IsNan and Is{Positive,Negative}Infinity
See also https://github.com/dotnet/efcore/issues/22167, https://github.com/oracle/dotnet-db-samples/issues/93
=> Handle special floating point values

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
=> Translate date time ctor

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs
Because of changes in EF Core 5.0.0
Fixes #1474
=> Fixes to annotation code generation

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
When inserting explicit IDs (during seeding), PostgreSQL doesn't update the sequence value for auto-generated columns; this results in unique constraint violations when the user next attempts to insert a new entity.
Detect all auto-generated columns of tables which were seeded in a migration, and reset their values to the current maximum.
Fixes #367
=> Automatically set sequence value after seeding

Directory.Build.props
https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/
=> Opt into the latest warning levels

src/EFCore.PG/Extensions/NpgsqlDbFunctionsExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindDbFunctionsQueryNpgsqlTest.cs
=> Add EF.Functions.Reverse(string)

src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Correctly look up column names with new relational model

src/EFCore.PG/Query/Expressions/Internal/PostgresArrayIndexExpression.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayListTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Also cleaned up some value comparer logic which wasn't getting used at all.
Closes #1025
=> Support for nullable arrays and hash code calculation

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fixes around array.Any translation

src/EFCore.PG.NodaTime/Storage/Internal/NodaTimeMappings.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
=> Code literal generation for NodaTime Period

src/EFCore.PG.NodaTime/Storage/Internal/NodaTimeMappings.cs, src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs, src/EFCore.PG/Query/Expressions/Internal/PostgresFunctionExpression.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs, test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
Closes #1567
Closes #1565
/cc @smitpatel @ajcvickers for some NodaTime goodness
=> More NodaTime arithmetic and support for Duration

src/EFCore.PG/Query/Internal/NpgsqlParameterBasedSqlProcessor.cs
=> Make ParameterBasedSqlProcessor thread safe

src/EFCore.PG/Internal/IReadOnlyListExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/Expressions/Internal/PostgresAllExpression.cs, src/EFCore.PG/Query/Expressions/Internal/PostgresAnyExpression.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/QueryFilterFuncletizationNpgsqlTest.cs
=>  Work on array/list translation 

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs
=> Fix exception when value generation strategy is None

src/EFCore.PG/Extensions/TypeExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/ValueConversion/NpgsqlArrayConverter.cs, src/EFCore.PG/Storage/ValueConversion/NpgsqlValueConverterSelector.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fully support generic Lists in value conversion

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fix List.Contains for Any/Contains (array overlap) scenario

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/MigrationsNpgsqlTest.cs
Fixes #1631
We should add test coverage, opened https://github.com/dotnet/efcore/issues/23811 to track upstream support for this.
=> Fix seeding with idempotent migrations

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/NpgsqlDatabaseCreatorTest.cs, test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlTestStore.cs
And reintroduce new NpgsqlDatabaseCreatorTest suite
Closes #1635
=> Use DROP DATABASE ... FORCE on PG13

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/FunkyDataQueryNpgsqlTest.cs
Fixes #1563
~Note: based off of #1643~
=> Fix parameterized StartsWith with backslash

Directory.Build.targets, test/EFCore.PG.FunctionalTests/NpgsqlApiConsistencyTest.cs, test/EFCore.PG.FunctionalTests/Query/UdfDbFunctionNpgsqlTests.cs, test/EFCore.PG.FunctionalTests/SeedingNpgsqlTest.cs
Commit 918f7b52483c752a8004b04391477490bc3e700e
=> Sync to 6.0.0-alpha.1.21065.5

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs, test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs
=> Support PG extensions with schema

src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs
=> Fix broken NewArray type mapping logic

src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
=> Fix array list mapping when store type is specified

Directory.Build.targets, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlEntityTypeExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlIndexExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlModelExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlPropertyExtensions.cs, src/EFCore.PG/Metadata/CockroachDbInterleaveInParent.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlSharedTableConvention.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationConvention.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlValueGenerationStrategyConvention.cs, src/EFCore.PG/Metadata/Internal/IdentitySequenceOptionsData.cs, src/EFCore.PG/Metadata/Internal/NpgsqlIndexExtensions.cs, src/EFCore.PG/Metadata/PostgresCollation.cs, src/EFCore.PG/Metadata/PostgresEnum.cs, src/EFCore.PG/Metadata/PostgresExtension.cs, src/EFCore.PG/Metadata/PostgresRange.cs, test/EFCore.PG.FunctionalTests/NpgsqlApiConsistencyTest.cs, test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs, test/EFCore.PG.Tests/Metadata/NpgsqlMetadataExtensionsTest.cs
Commit b8483772f298f5ada8b2b5253a9904c93c34919f
=> Sync to 6.0.0-preview.2.21102.1

src/EFCore.PG/Metadata/NpgsqlValueGenerationStrategy.cs, src/EFCore.PG/Metadata/NullSortOrder.cs, src/EFCore.PG/Metadata/SortOrder.cs, src/EFCore.PG/Utilities/SortOrderHelper.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsInfrastructureNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
=> Move some public enums to Microsoft.EntityFrameworkCore.Metadata

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs
=> Translate array containment on List<T>

src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlPropertyBuilderExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayListTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, src/EFCore.PG/Storage/ValueConversion/INpgsqlArrayConverter.cs, src/EFCore.PG/Storage/ValueConversion/NpgsqlArrayConverter.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Improved support for value-converted arrays and lists

src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
See https://github.com/dotnet/efcore/pull/24209
Depends on https://github.com/npgsql/npgsql/pull/3570
=> Don't access Transaction.Current if Enlist=false

src/EFCore.PG/Storage/Internal/INpgsqlRelationalConnection.cs, src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs, src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
Plus other refactoring
Closes #1756
=> Use RelationalConnection in NpgsqlDatabaseCreator.Exists

src/.editorconfig, src/EFCore.PG.NTS/Storage/Internal/NpgsqlNetTopologySuiteTypeMappingSourcePlugin.cs, src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs, src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonDomTranslator.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs, src/EFCore.PG/Storage/Internal/NpgsqlExecutionStrategy.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs, src/EFCore.PG/ValueGeneration/Internal/NpgsqlSequenceHiLoValueGenerator.cs
=> Apply ConfigureAwait(false) and ordinal string operations

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDecimalTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlMoneyTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
* Fix store type name generation for timestamp
* Refactor store type name generation
* Properly flow facets to array element mappings
Fixes #1775
=> Fixes to precision/scale handling in type mappings

src/EFCore.PG/Migrations/Internal/NpgsqlHistoryRepository.cs
=> Change idempotent quoting tag to $EF$

Directory.Packages.props, src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/EnumQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/FieldsOnlyLoadNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/InheritanceQueryNpgsqlFixture.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonStringQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/LTreeQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ManyToManyFieldsLoadNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NetworkQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindAggregateOperatorsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs, test/EFCore.PG.FunctionalTests/WithConstructorsNpgsqlTest.cs
EFCore -> 6.0.0-preview.4.21208.112 (d240c89f87973571054572f487131b202d60bcb5)
MicrosoftExtensions -> 6.0.0-preview.4.21205.1
Npgsql -> 6.0.0-ci.20210408T104816
=> Bump dependencies

src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayListTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fixes around arrays and value converters

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
=> Properly reverse-engineer views

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fix array Contains with scalar subquery

Directory.Build.props, Directory.Packages.props, src/EFCore.PG/Design/Internal/NpgsqlDesignTimeServices.cs
EFCore -> 6.0.0-preview.4.21216.2 (633d67339ac29939b78a4db5af79a143438bd9d4)
MicrosoftExtensions -> 6.0.0-preview.4.21216.6
Npgsql -> 6.0.0-ci.20210415T191850
=> Bump dependencies, branching for preview4

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
=> Add foreign tables to DatabaseModel

src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
=> Don't log an error in database existence check

src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
=> Fix JSON nullability processing

src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs, test/EFCore.PG.Tests/Storage/NpgsqlRelationalConnectionTest.cs
=> Fix NpgsqlRelationalConnection.CloneWith

src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs, test/EFCore.PG.FunctionalTests/NpgsqlDatabaseCreatorTest.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs, test/EFCore.PG.FunctionalTests/TestUtilities/RequiresPostgisAttribute.cs
=> Exclude extension tables when checking if tables exist

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
=> Properly ignore extension-owned tables when scaffolding

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
=> Support DateTimeOffset in JSON documents

src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlFullTextSearchDbFunctionsExtensions.cs, test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
=> Don't parameterize full-text search config

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/TestUtilities/NpgsqlDatabaseCleaner.cs
=> fix: in Redshift compatibility mode, do not retrieve collations

src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, test/EFCore.PG.Tests/NpgsqlDbContextOptionsExtensionsTest.cs
=> Add NpgsqlServiceCollectionExtensions.AddNpgsql

.github/workflows/build.yml, Directory.Build.props, Directory.Packages.props, global.json, src/EFCore.PG.NTS/EFCore.PG.NTS.csproj, src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj, src/EFCore.PG/EFCore.PG.csproj, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMathTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/Directory.Build.props, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPTGearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.Tests/EFCore.PG.Tests.csproj, test/EFCore.PG.Tests/Scaffolding/NpgsqlCodeGeneratorTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs, test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchFactoryTest.cs, test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchTest.cs
Includes support for MathF translations.
Closes #1833
=> Sync to 6.0.0-preview6

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
Fixes #1942
Fixes #1946
Fixes #1947
=> Various fixes to computed columns

src/EFCore.PG/Metadata/Conventions/NpgsqlConventionSetBuilder.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlRuntimeModelConvention.cs
=> Implement NpgsqlRuntimeModelConvention

src/EFCore.PG/Metadata/Conventions/NpgsqlSharedTableConvention.cs
=> Disable check constraint uniquification across tables

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs
Following https://github.com/dotnet/efcore/pull/26136
=> Fix snapshot generation with HiLo

src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs, src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMethodCallTranslatorPlugin.cs, src/EFCore.PG.NodaTime/Storage/Internal/DateIntervalMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs, test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
Fixes #1998
Replaces #1670
Co-authored-by: Shay Rojansky <roji@roji.org>
=> Add support for Noda.DateInterval

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterCharMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterStringTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlStringTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
=> Fix non-text string type mappings to send NpgsqlDbType

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterCharMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCharacterStringTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlStringTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
Fixes #2010
(cherry picked from commit 2427545ac7f51e6940bbb6d38932c874bae2681a)
=> Fix non-text string type mappings to send NpgsqlDbType (#2011)

EFCore.PG.sln.DotSettings, src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlMultirangeDbFunctionsExtensions.cs, src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlRangeDbFunctionsExtensions.cs, src/EFCore.PG/Extensions/TypeExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRangeTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlMultirangeTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/Query/MultirangeQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs, test/EFCore.PG.FunctionalTests/TestUtilities/TestEnvironment.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Plus some range improvements
Closes #1963
Fixes #2014
=> Multirange support

src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> Fix daterange mapping

src/EFCore.PG.NodaTime/Storage/Internal/DateIntervalMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/DateMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/DurationIntervalMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/LegacyTimestampInstantMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs, src/EFCore.PG.NodaTime/Storage/Internal/PeriodIntervalMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimeTzMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampLocalDateTimeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampTzInstantMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampTzOffsetDateTimeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampTzZonedDateTimeMapping.cs, src/EFCore.PG/Extensions/RelationalTypeMappingExtensions.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeTypeMappings.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRangeTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTypeMapping.cs, test/EFCore.PG.FunctionalTests/Query/RangeQueryNpgsqlTest.cs, test/EFCore.PG.NodaTime.FunctionalTests/LegacyNpgsqlNodaTimeTypeMappingTest.cs, test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> Redo range SQL literal generation

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> Translate DateTime.SpecifyKind

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, test/EFCore.PG.FunctionalTests/ValueConvertersEndToEndNpgsqlTest.cs
=> Remove incorrect array conversion nullability safety check

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlBigIntegerMemberTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMathTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBigIntegerTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/BuiltInDataTypesNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/BigIntegerQueryTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
Mapping plus some basic translations.
Closes #2081
=> Support BigInteger

src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs, src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMethodCallTranslatorPlugin.cs, src/EFCore.PG.NodaTime/Query/Internal/PendingZonedDateTimeExpression.cs, test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
=> Support non-constant time zones in NodaTime translations

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
=> Recreate indexes after dropping/creating computed columns

EFCore.PG.sln.DotSettings, src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, src/EFCore.PG/Query/Expressions/Internal/PostgresRowValueExpression.cs, src/EFCore.PG/Query/Internal/NpgsqlPostgresSqlOptimizingVisitor.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs, src/EFCore.PG/Query/Internal/NpgsqlQueryTranslationPostprocessor.cs, src/EFCore.PG/Query/Internal/NpgsqlQueryTranslationPostprocessorFactory.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/PostgresOptimizationsQueryTest.cs
=> Pattern-match to PG row value comparison

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs, test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs
=> Add some missing translations for DateTimeOffset

src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fix array containment type mapping inference around conversion

src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
=> Fix exists for multiple hosts

EFCore.PG.sln.DotSettings, src/EFCore.PG/Types/LTree.cs, test/EFCore.PG.Tests/Types/LTreeTest.cs
=> Fix LTree.ToString

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs
=> Additional translations for DateOnly/TimeOnly

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
=> Fix enum scaffolding for PG < 9.1

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
=> Don't reverse-engineer collations for PG < 9.1

.github/workflows/build.yml
=> Bump github actions versions

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
=> Change method of ensuring a schema

src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj, src/EFCore.PG.NodaTime/Storage/Internal/DateIntervalMultirangeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/DateIntervalRangeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/IntervalMultirangeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/IntervalRangeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlMultirangeTypeMapping.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs
=> Multirange support for NodaTime

src/EFCore.PG.NTS/Scaffolding/Internal/NpgsqlNetTopologySuiteCodeGeneratorPlugin.cs, test/EFCore.PG.Tests/Scaffolding/NpgsqlCodeGeneratorTest.cs
Following https://github.com/dotnet/efcore/pull/26160
=> Fix NTS scaffolding code generation

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
=> Stop scaffolding index included/covered properties

src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
=> Fix Redshift options configuration

src/EFCore.PG/Storage/ValueConversion/NpgsqlArrayConverter.cs, test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryFixture.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/TestModels/Array/ArrayEntity.cs, test/EFCore.PG.FunctionalTests/TestModels/Array/ArrayQueryContext.cs, test/EFCore.PG.FunctionalTests/TestModels/Array/ArrayQueryData.cs
=> Fix value conversion of array over nullable

src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlEntityTypeBuilderExtensions.cs
=> Correct doc link

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPTGearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs
=> Fix DateTimeOffset.Date translation

Directory.Packages.props, test/EFCore.PG.FunctionalTests/Migrations/NpgsqlMigrationsSqlGeneratorTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindMiscellaneousQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindSelectQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindSetOperationsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/SimpleQueryNpgsqlTest.cs
EF Core -> 7.0.0-preview.1.22071.1
Npgsql -> 7.0.0-preview.1-ci.20220123T182030
=> Sync dependencies

src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlTimeSpanMemberTranslator.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
=> Translate Total* members on TimeSpan

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/Migrations/NpgsqlMigrationsSqlGeneratorTest.cs
=> Fix ensuring schema in idempotent migrations

src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlModelBuilderExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlModelExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlPropertyExtensions.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlRuntimeModelConvention.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
=> Obsolete default column collations

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/TestModels/Array/ArrayQueryContext.cs
=> Fix issues with value-converted arrays

Directory.Packages.props, src/EFCore.PG/Update/Internal/NpgsqlModificationCommandBatch.cs, src/EFCore.PG/Update/Internal/NpgsqlUpdateSqlGenerator.cs, test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsSharedTypeQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/Ef6GroupByNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/StoreGeneratedNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs, test/EFCore.PG.FunctionalTests/Update/StoreValueGenerationNpgsqlTest.cs, test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchFactoryTest.cs, test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchTest.cs
EF Core -> 7.0.0-preview.3.22175.1
=> Sync dependencies and update SQL generation improvements

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlObjectToStringTranslator.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fixes around casting to string and inferring array mapping

.github/workflows/build.yml, Directory.Packages.props, NuGet.config, global.json
And stop explicitly specifying the version in our CI workflow (use global.json)
=> Bump dotnet SDK to 7.0.100-preview.4.22252.9

src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, src/EFCore.PG/Infrastructure/Internal/INpgsqlSingletonOptions.cs, src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs, src/EFCore.PG/Infrastructure/NpgsqlModelValidator.cs, src/EFCore.PG/Internal/NpgsqlSingletonOptions.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlConventionSetBuilder.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMemberTranslatorProvider.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMethodCallTranslatorProvider.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlNewGuidTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlRangeTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGeneratorFactory.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs, test/EFCore.PG.NodaTime.FunctionalTests/LegacyNpgsqlNodaTimeTypeMappingTest.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs, test/EFCore.PG.Tests/Design/Internal/NpgsqlAnnotationCodeGeneratorTest.cs, test/EFCore.PG.Tests/NpgsqlRelationalConnectionTest.cs, test/EFCore.PG.Tests/Storage/LegacyNpgsqlTypeMappingTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs, test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchFactoryTest.cs, test/EFCore.PG.Tests/Update/NpgsqlModificationCommandBatchTest.cs
=> Don't map to multiranges when PG version is explicitly set to < 14

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
Not doing array_to_tsvector support for now, since it doesn't accept a search configuration.
Closes #2215
=> Support JSON columns in full-text search generated columns

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlLTreeTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs
/cc @smitpatel, FYI here's the modified handling of that up-cast Convert node, as discussed in https://github.com/dotnet/efcore/pull/27964
=> Refactor row value comparison

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonPocoTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonDomQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/JsonPocoQueryTest.cs
=> Translate List.Count inside json

Directory.Packages.props, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlMathTranslator.cs, src/EFCore.PG/Query/Internal/NpgsqlParameterBasedSqlProcessor.cs, test/EFCore.PG.FunctionalTests/Migrations/NpgsqlMigrationsSqlGeneratorTest.cs, test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsCollectionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPCGearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPTGearsOfWarQueryNpgsqlTest.cs
And fix Math.Round/Truncate over decimal.
Fixes #2379
=> Sync EF Core to 7.0.0-preview.5.22274.2

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTimestampTzTypeMapping.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> General infinity literals for DateTimeOffset min/max values

src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayArrayTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayListTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fix inference between CLR array and list

Directory.Packages.props, src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs, src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeographyTest.cs, test/EFCore.PG.FunctionalTests/Query/SpatialQueryNpgsqlGeometryTest.cs
=> Translate EnvelopeCombiner.CombineAsGeometry

.github/workflows/build.yml, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindGroupByQueryNpgsqlTest.cs
And react to PG15 ICU collation changes
=> Test on PG15 beta

src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs
=> Fix silly bug in nullability processing

src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs
=> Don't scaffold enums on very old PG

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
=> Translate DateTime.Date when mapped to PG date

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Fix post-seeding sequence bumping logic

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlJsonDbFunctionsTranslator.cs, test/EFCore.PG.FunctionalTests/Query/JsonStringQueryTest.cs
=> Make sure text is converted to jsonb when passed as a JSON function argument

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Use platform newline in schema ensure migrations SQL

src/EFCore.PG.NTS/Query/ExpressionTranslators/Internal/NpgsqlNetTopologySuiteMethodCallTranslatorPlugin.cs, src/EFCore.PG.NodaTime/Extensions/NpgsqlNodaTimeDbFunctionsExtensions.cs, src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMethodCallTranslatorPlugin.cs, src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlDbFunctionsExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs, src/EFCore.PG/Query/Expressions/Internal/PostgresBinaryExpression.cs, src/EFCore.PG/Query/Expressions/PostgresExpressionType.cs, src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, test/EFCore.PG.FunctionalTests/Northwind.sql, test/EFCore.PG.FunctionalTests/Query/NorthwindDbFunctionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/TestModels/Northwind/NorthwindNpgsqlContext.cs, test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
When used with the btree_gist extension.
Closes #2523
=> Add date/time support for the distance operator

src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs
=> Remove composability check override

src/EFCore.PG/Infrastructure/Internal/NpgsqlModelValidator.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs, src/EFCore.PG/Properties/NpgsqlStrings.Designer.cs, src/EFCore.PG/Properties/NpgsqlStrings.resx, src/EFCore.PG/Update/Internal/NpgsqlModificationCommand.cs
=> Block EF7 JSON usage

src/EFCore.PG/Query/Expressions/Internal/PostgresRowValueExpression.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlRowValueTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindAggregateOperatorsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindWhereQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPCGearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPTGearsOfWarQueryNpgsqlTest.cs
Which means they can now be projected out etc.
Closes #2356
=> Implement full type mapping for row values

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlArrayTranslator.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindFunctionsQueryNpgsqlTest.cs
Translate to concat_ws for the simple case
Closes #2485
=> Improve non-aggregate string.Join translations

src/EFCore.PG/Design/Internal/NpgsqlAnnotationCodeGenerator.cs, src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlIndexBuilderExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlIndexExtensions.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlRuntimeModelConvention.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationNames.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Scaffolding/NpgsqlDatabaseModelFactoryTest.cs
=> Add support for specifying NULLS NOT DISTINCT for unique indexes

src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs
=> Fix DbDataSource management in NpgsqlOptionsExtension

src/EFCore.PG/Utilities/SortOrderHelper.cs
=> Recognize empty index descending array in IsDefaultNullSortOrder

src/EFCore.PG.NodaTime/Storage/Internal/LegacyTimestampInstantMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/NpgsqlNodaTimeTypeMappingSourcePlugin.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimeTzMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampLocalDateTimeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampTzInstantMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampTzOffsetDateTimeMapping.cs, src/EFCore.PG.NodaTime/Storage/Internal/TimestampTzZonedDateTimeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTimeTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTimeTzTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.NodaTime.FunctionalTests/NpgsqlNodaTimeTypeMappingTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> Correct date/time mapping with precision

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlULongTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs
=> Support xid8

src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlDbFunctionsExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlStringMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindDbFunctionsQueryNpgsqlTest.cs
=> Add translation for StringToArray

src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, src/EFCore.PG/Infrastructure/Internal/DataSourceWrapper.cs, src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs, src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs, test/EFCore.PG.FunctionalTests/TestUtilities/TestNpgsqlConnection.cs, test/EFCore.PG.Tests/NpgsqlRelationalConnectionTest.cs
=> Fix data source management

src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs, src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMethodCallTranslatorPlugin.cs, test/EFCore.PG.NodaTime.FunctionalTests/NodaTimeQueryNpgsqlTest.cs
=> Allow all date/time members on result of NodaTime InZone

src/EFCore.PG/Query/Expressions/Internal/PostgresNewArrayExpression.cs, test/EFCore.PG.FunctionalTests/Query/ArrayQueryTest.cs
=> Fix bug in NewArrayExpression.VisitChildren

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDecimalTypeMapping.cs, src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingSourceTest.cs, test/EFCore.PG.Tests/Storage/NpgsqlTypeMappingTest.cs
=> Allow mapping decimal to float/double

src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs
=> Fix NodaTime Date translation for legacy timestamp mode

src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs
=> Fix translation of Take over array

src/EFCore.PG/Extensions/DbFunctionsExtensions/NpgsqlFullTextSearchLinqExtensions.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlFullTextSearchMethodTranslator.cs, test/EFCore.PG.FunctionalTests/Query/FullTextSearchDbFunctionsNpgsqlTest.cs
I'm not sure what the etiquette is here.
Unfortunately I was not able to get `main` to build/test on my Linux system with preview 8. However I was able to apply and verify the original and new rewrite tests pass on `v7.0.4`..
=> Add NpgsqlTsQuery.Rewrite select form

src/EFCore.PG.NodaTime/Query/Internal/NpgsqlNodaTimeMemberTranslatorPlugin.cs, src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPCGearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TPTGearsOfWarQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/TimestampQueryTest.cs
=> Various date/time timezone-related fixes

src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlEntityTypeBuilderExtensions.cs, src/EFCore.PG/Extensions/BuilderExtensions/NpgsqlIndexBuilderExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlEntityTypeExtensions.cs, src/EFCore.PG/Extensions/MetadataExtensions/NpgsqlIndexExtensions.cs, src/EFCore.PG/Metadata/Conventions/NpgsqlRuntimeModelConvention.cs, src/EFCore.PG/Metadata/Internal/NpgsqlAnnotationProvider.cs, src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs, src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs, test/EFCore.PG.FunctionalTests/Migrations/MigrationsNpgsqlTest.cs
And scaffold storage parameters for both tables and indices.
Closes #2899
Closes #2913
=> Add support for index storage parameters and for scaffolding

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/OptionalDependentQueryNpgsqlTest.cs
=> Workaround for comparing owned JSON entity type to null

src/EFCore.PG/Extensions/NpgsqlServiceCollectionExtensions.cs, src/EFCore.PG/Migrations/Internal/NpgsqlMigrator.cs, src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs
=> Call Npgsql's ReloadTypes as needed from programmatic Migrate()

src/EFCore.PG/Extensions/NpgsqlDbContextOptionsBuilderExtensions.cs
=> Allow transfer of ownership of DbConnection from application to DbContext

src/EFCore.PG/Extensions/ExpressionVisitorExtensions.cs, src/EFCore.PG/Query/Expressions/Internal/PgTableValuedFunctionExpression.cs, src/EFCore.PG/Query/Expressions/Internal/PgUnnestExpression.cs
=> Properly implement VisitChildren on PG TVF expressions

src/EFCore.PG/Design/Internal/NpgsqlCSharpRuntimeAnnotationCodeGenerator.cs, src/EFCore.PG/Design/Internal/NpgsqlDesignTimeServices.cs
=> Add NpgsqlCSharpRuntimeAnnotationCodeGenerator

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMethodTranslator.cs, src/EFCore.PG/Query/NpgsqlSqlExpressionFactory.cs, test/EFCore.PG.FunctionalTests/Query/GearsOfWarQueryNpgsqlTest.cs
=> Fix DateOnly.Add{Days,Months,Years}

src/EFCore.PG/Migrations/NpgsqlMigrationsSqlGenerator.cs
=> Fix adding a new non-nullable JSON column

src/EFCore.PG/Query/Internal/NpgsqlQuerySqlGenerator.cs, test/EFCore.PG.FunctionalTests/Query/OperatorsQueryNpgsqlTest.cs
Fixes #2980
[See this discussion](https://www.postgresql.org/message-id/CADT4RqBPdbsZW7HS1jJP319TMRHs1hzUiP=iRJYR6UqgHCrgNQ@mail.gmail.com)
=> Fix operator precedence of AT TIME ZONE

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/FunkyDataQueryNpgsqlTest.cs
=> Add method postfix when rewriting parameters for StartsWith/EndsWith/Contains

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlBigIntegerTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlCidrTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateOnlyTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlDateTimeDateTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlInetTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlIntervalTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlLTreeTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlPgLsnTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTimeTzTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTimestampTypeMapping.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlTimestampTzTypeMapping.cs
=> Make Npgsql-specific JsonValueReaderWriters public for compiled model

src/EFCore.PG/Design/Internal/NpgsqlCSharpRuntimeAnnotationCodeGenerator.cs, src/EFCore.PG/Storage/Internal/Mapping/NpgsqlUIntTypeMapping.cs
=> Support NpgsqlUIntTypeMapping for the compiled model

src/EFCore.PG/Query/ExpressionTranslators/Internal/NpgsqlDateTimeMemberTranslator.cs
=> Translate DateTime.Date without type mapping in legacy mode

src/EFCore.PG/Query/Internal/NpgsqlSqlNullabilityProcessor.cs, test/EFCore.PG.FunctionalTests/Query/NorthwindDbFunctionsQueryNpgsqlTest.cs
=> Fix null semantics for ILikeExpression

src/EFCore.PG/Storage/ValueConversion/NpgsqlArrayConverter.cs
=> Remove incorrect variable declaration in NpgsqlArrayConverter

src/EFCore.PG/Query/Internal/NpgsqlSqlTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/CitextQueryTest.cs
=> Remove unneeded backslash ESCAPE from LIKE translations

src/EFCore.PG/Storage/Internal/INpgsqlRelationalConnection.cs, src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs
=> Make INpgsqlRelationalConnection.CloneWith return INpgsqlRelationalConnection

src/EFCore.PG/EFCore.PG.csproj
=> Remove direct dependency on EFCore.Abstractions

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs, src/EFCore.PG/Storage/ValueConversion/NpgsqlArrayConverter.cs, test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs
=> Support arbitrary enumerables in NpgsqlArrayConverter

src/EFCore.PG/Storage/Internal/INpgsqlRelationalConnection.cs, src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs, src/EFCore.PG/Storage/Internal/NpgsqlRelationalConnection.cs, test/EFCore.PG.Tests/NpgsqlRelationalConnectionTest.cs
=> Use Npgsql's new CloneWithAsync

src/EFCore.PG/Storage/Internal/Mapping/NpgsqlArrayTypeMapping.cs
=> Fix arrays over user-defined ranges

src/EFCore.PG/Migrations/Internal/NpgsqlMigrator.cs
=> Don't open connection if already open when reloading types

src/EFCore.PG/Storage/Internal/NpgsqlTypeMappingSource.cs
=> Add tstzrange to NpgsqlRange<DateTimeOffset>

src/EFCore.PG/Metadata/Conventions/NpgsqlJsonElementHackConvention.cs
=> Fix error around mapping Nullable<JsonElement>

src/EFCore.PG/Query/Internal/NpgsqlParameterBasedSqlProcessorFactory.cs
=> Restore virtual modifier

src/EFCore.PG/Infrastructure/Internal/NpgsqlOptionsExtension.cs, test/EFCore.PG.Tests/NpgsqlDbContextOptionsExtensionsTest.cs
=> Stop include data source connection string in service provider hashcode

src/EFCore.PG/Metadata/Conventions/NpgsqlRuntimeModelConvention.cs, src/EFCore.PG/Query/Internal/NpgsqlQueryableMethodTranslatingExpressionVisitor.cs, test/EFCore.PG.FunctionalTests/Query/ArrayArrayQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/ArrayListQueryTest.cs, test/EFCore.PG.FunctionalTests/Query/NonSharedPrimitiveCollectionsQueryNpgsqlTest.cs, test/EFCore.PG.FunctionalTests/Query/PrimitiveCollectionsQueryNpgsqlTest.cs
=> Vary array containment translation based on indexes
